'use strict';
(()=>{const D=window.MakmalYear4Domains,ui=window.MakmalYear4UI,b=ui.button;
 const sequential={init(){},solved:(s,d)=>Object.keys(s.done).length===d.actions.length,act(s,d,a,v){if(a!=='do')return;const next=d.actions[Object.keys(s.done).length];if(next?.id===v){s.done[v]=true;ui.message(s,next.note);s.effect='observation';}else ui.message(s,'Ikut urutan bukti yang sesuai. Periksa langkah sebelumnya.',false);},hint(s,d){const x=d.actions[Object.keys(s.done).length];return x?['do',x.id,'Cuba '+x.label+'.']:['next',undefined,'Semua bukti direkod.'];},render(s,d,active){return ui.scene(d,s)+`<div class="y4-action-grid">${d.actions.map((x,i)=>`<button class="y4-action" data-exp="do" data-value="${x.id}" ${!active||s.done[x.id]?'disabled':''}><span>${ui.art(x.art)}<strong>${x.label}</strong></span><small>${s.done[x.id]?'✓ '+x.note:i===Object.keys(s.done).length?'Tindakan seterusnya':'Belum diuji'}</small></button>`).join('')}</div>`;}};
 ['sequence','checklist','compare','investigate'].forEach(mode=>D[mode]=mode==='checklist'?{...sequential,act(s,d,a,v){if(a==='do'&&d.actions.some(x=>x.id===v)&&!s.done[v]){s.done[v]=true;ui.message(s,d.actions.find(x=>x.id===v).note);s.effect='observation';}},hint(s,d){const x=d.actions.find(x=>!s.done[x.id]);return x?['do',x.id,'Cuba '+x.label+'.']:['next',undefined,'Semua bukti direkod.'];}}:sequential);
 const classify={init(){},solved:(s,d)=>Object.keys(s.matched).length===d.actions.length,act(s,d,a,v){if(a==='choose'&&d.actions.some(x=>x.id===v)&&!s.matched[v]){s.selected=v;s.message='Periksa bukti sebelum mengelaskan.';}if(a==='inspect'&&s.selected){s.inspected[s.selected]=true;s.message=d.actions.find(x=>x.id===s.selected).note;s.effect='observation';}if(a==='assign'&&s.selected&&s.inspected[s.selected]){const x=d.actions.find(x=>x.id===s.selected);if(x.target===v){s.matched[x.id]=v;s.selected=null;ui.message(s,'✓ Padanan disimpan berdasarkan bukti.');s.effect='classification';}else ui.message(s,'Kumpulan itu tidak sepadan dengan bukti. Cuba lagi.',false);}},hint(s,d){const x=d.actions.find(x=>x.id===s.selected)||d.actions.find(x=>!s.matched[x.id]);if(!s.selected)return ['choose',x.id,'Pilih '+x.label+'.'];if(!s.inspected[x.id])return ['inspect',undefined,'Periksa bukti.'];return ['assign',x.target,'Pilih kumpulan yang sepadan.'];},render(s,d,active){const x=d.actions.find(x=>x.id===s.selected),targets=[...new Set(d.actions.map(x=>x.target))];return ui.scene(d,s)+`<div class="y4-cards">${d.actions.map(x=>`<button class="y4-card" data-exp="choose" data-value="${x.id}" aria-pressed="${s.selected===x.id}" ${!active||s.matched[x.id]?'disabled':''}>${ui.art(x.art)}<strong>${x.label}</strong><small>${s.matched[x.id]?'✓ '+label(x.target):'Pilih dan periksa'}</small></button>`).join('')}</div>${x?`<section class="y4-evidence"><strong>${x.label}</strong>${b('inspect',undefined,'🔎 Periksa bukti',!active||s.inspected[x.id])}<p>${s.inspected[x.id]?x.note:'Bukti belum diperiksa.'}</p></section>`:''}<div class="y4-targets">${targets.map(t=>b('assign',t,label(t),!active||!x||!s.inspected[x.id])).join('')}</div>`;}};
 function label(id){return ({observe:'Pemerhatian',infer:'Inferens',manipulated:'Dimanipulasikan',responding:'Bergerak balas',controlled:'Dimalarkan',yes:'Sesuai / boleh diuji',no:'Tidak sesuai',inhale:'Udara sedutan',exhale:'Udara hembusan',gills:'Insang',lungs:'Peparu',spiracles:'Spirakel',skin:'Kulit lembap',vertebrate:'Vertebrata',invertebrate:'Invertebrata',mammal:'Mamalia',bird:'Burung',reptile:'Reptilia',amphibian:'Amfibia',fish:'Ikan',useful:'Berfaedah',harmful:'Memudaratkan',natural:'Sumber semula jadi',stored:'Tenaga tersimpan',light:'Cahaya',heat:'Haba',kinetic:'Kinetik',sound:'Bunyi',renewable:'Boleh dibaharui',nonrenewable:'Tidak boleh dibaharui',plant:'Tumbuhan',animal:'Haiwan',rock:'Batuan',petroleum:'Petroleum',inclined:'Satah condong',wedge:'Baji',wheel:'Roda dan gandar',screw:'Skru',gear:'Gear',complex:'Mesin kompleks',simple:'Mesin ringkas'})[id]||id.replaceAll('-',' ');}
 ['classify','select'].forEach(mode=>D[mode]=classify);
 D['fair-test']=D.checklist;D.evidence=classify;D.variables=classify;D.design=classify;
 ['inquiry','breathing','breathing-rate','animals','plant-response','photosynthesis','light4','sound4','energy4','materials4','earth4','machines4','lever4'].forEach(mode=>D[mode]=sequential);
})();
