 'use strict';
// Presentation only: objectives and PICO voice. Science rules live in unit modules.
window.MakmalExperienceContent = {
 'electricity-1':{objective:'Kenali empat alat dan kegunaannya dalam litar.',discovery:'Bateri membekalkan tenaga, wayar menyambung, suis mengawal dan mentol menghasilkan cahaya.',lines:['Alat mana agaknya membekalkan tenaga?','Lihat bentuknya. Padankan label dengan alat.','Mari kenali kegunaan setiap alat.','Apa berlaku jika wayar tidak bersambung?','Empat alat sudah kamu kenali. Sedia untuk membina litar!']},
 'electricity-2':{objective:'Sambungkan tiga wayar dan nyalakan mentol.',discovery:'Litar lengkap dan suis tertutup membolehkan mentol menyala.',lines:['Boleh kamu nyalakan mentol ini?','Ikut laluan bertitik. Sambungkan wayar, kemudian tutup suis.','Perhatikan peranan setiap bahagian litar.','Lihat suis itu. Mengapa mentol padam?','Litar kamu lengkap dan mentol menyala!']},
 'electricity-3':{objective:'Cari dan baiki satu sambungan yang terputus.',lines:['Oh, mentol padam! Apa yang tidak kena?','Cari satu laluan yang terputus.','Sambungan dibaiki, mentol kembali menyala.','Ingat keadaan litar sebelum dibaiki.','Kamu jumpa puncanya dan berjaya membaikinya.']},
 'electricity-4':{objective:'Bandingkan mentol apabila suis dibuka dan ditutup.',lines:['Apa berubah apabila kita mengubah suis?','Cuba kedua-dua keadaan. Kamu boleh ulang sesuka hati.','Bandingkan suis terbuka dan tertutup.','Apakah tugas suis dalam litar?','Kini kamu tahu bagaimana suis mengawal litar.']},
 'electricity-5':{objective:'Baiki lampu makmal dengan melengkapkan litar.',lines:['Lampu makmal terputus! Boleh kamu bantu?','Periksa sambungan dan suis.','Lampu kembali menyala. Mari lihat sebabnya.','Bagaimana jika satu wayar tercabut?','Lampu pulih! Kamu sudah boleh mengenal, membina dan membaiki litar.']},
 'light-dark-1':{objective:'Kelaskan lima objek sebagai sumber cahaya atau bukan sumber cahaya.',lines:['Objek mana menghasilkan cahaya sendiri?','Pilih objek, kemudian pilih kumpulannya.','Ada yang menghasilkan cahaya, ada yang memantulkannya.','Fikirkan Bulan pada waktu malam.','Kamu sudah mengenali sumber cahaya di sekeliling kita.']},
 'light-dark-2':{objective:'Gunakan lampu suluh untuk melihat tiga bahagian bilik.',lines:['Gelapnya! Apa boleh membantu kita melihat?','Suluh kiri, tengah dan kanan.','Lihat perbezaan sebelum dan selepas ada cahaya.','Mengapa objek tadi sukar dilihat?','Bilik terang, objek pun lebih jelas!']},
 'light-dark-3':{objective:'Letakkan bola dalam cahaya untuk menghasilkan bayang-bayang.',lines:['Apa agaknya muncul di belakang bola?','Cuba alihkan bola masuk dan keluar daripada cahaya.','Lihat sumber cahaya, bola dan bayangnya.','Apa yang menghalang cahaya tadi?','Kamu berjaya menghasilkan bayang-bayang sendiri.']},
 'light-dark-4':{objective:'Bandingkan cahaya melalui kadbod dan plastik jernih.',lines:['Adakah dua bahan ini memberi hasil yang sama?','Uji kedua-dua bahan. Perhatikan skrin.','Bandingkan bahagian terang dan gelap.','Bahan mana menghalang cahaya dengan lebih jelas?','Menarik, bahan berbeza memberi hasil berbeza!']},
 'light-dark-5':{objective:'Suluh bilik dan alihkan halangan untuk mencari kelalang PICO.',lines:['Kelalang saya hilang dalam gelap. Boleh bantu cari?','Lihat bayang di belakang kotak.','Cahaya sampai selepas kotak dialihkan.','Apa yang membantu kamu melihat kelalang?','Jumpa! Kamu menggunakan cahaya dan memahami bayangnya.']},
 'mixtures-1':{objective:'Kenal pasti tiga bahan dalam dulang campuran.',lines:['Boleh kenal pasti semua bahan di dalam dulang?','Perhatikan bentuk dan warna setiap bahan.','Lihat kumpulan bahan yang kamu temui.','Adakah campuran mempunyai satu bahan sahaja?','Tiga bahan ditemui dalam satu campuran!']},
 'mixtures-2':{objective:'Gunakan magnet untuk mengambil klip besi tanpa pasir.',lines:['Bagaimana hendak mengambil klip besi sahaja?','Pilih alat, kemudian gunakannya pada campuran.','Bandingkan sebelum dan selepas.','Mengapa klip besi terangkat?','Klip besi terasing, pasir masih di dalam dulang.']},
 'mixtures-3':{objective:'Ayak pasir dan kerikil menjadi dua kumpulan.',lines:['Pasir dan kerikil berbeza saiz. Alat mana sesuai?','Lihat bahan yang melalui lubang ayak.','Bandingkan bahan di atas dan di bawah ayak.','Mengapa pasir boleh melalui lubang itu?','Dua saiz, dua kumpulan. Pengasingan berjaya!']},
 'mixtures-4':{objective:'Uji gula, garam dan pasir dalam air baharu.',lines:['Ramalkan hasil setiap bahan, kemudian kita uji.','Tambah bahan dan kacau. Uji ketiga-tiganya.','Bandingkan hasil tiga ujian kamu.','Bahan mana masih kelihatan selepas dikacau?','Kamu sudah melihat bahan yang larut dan tidak larut.']},
 'mixtures-5':{objective:'Gunakan magnet dan ayak untuk mengasingkan tiga bahan.',lines:['Campuran ini perlukan lebih daripada satu cara.','Asingkan klip besi dahulu, kemudian baki campuran.','Lihat tiga kumpulan yang terhasil.','Mengapa satu cara sahaja belum mencukupi?','Pengasingan selesai! Kamu memilih cara yang sesuai untuk setiap bahan.']}
};
