const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
(async()=>{
 let back,resume,now=0,stops=0,exits=0,registrations=0,route='experiment',dialog,save={completed:true,completedAt:'original'};
 const controls={};for(const key of ['[data-stay]','[data-exit]'])controls[key]={addEventListener:(n,fn)=>controls[key].click=fn,focus(){}};
 const doc={documentElement:{classList:{add(){}}},getElementById:()=>({hidden:false}),body:{append(d){dialog=d;}},createElement:()=>({open:false,setAttribute(){},querySelector:s=>controls[s],showModal(){this.open=true;},close(){this.open=false;}})};
 const app={addListener:async(name,fn)=>{if(name==='backButton')back=fn;else if(name==='appStateChange')resume=fn;else assert.fail(name);registrations++;},exitApp:async()=>{exits++;}};
 const box={Date:{now:()=>now},window:{Capacitor:{isNativePlatform:()=>true,getPlatform:()=> 'android',Plugins:{App:app}},MakmalRewards:{stop:()=>stops++},MakmalRouter:{currentScreen:()=>route,back:()=>route=route==='experiment'?'unitDetail':route==='unitDetail'?'year2':route==='year2'?'yearSelect':route==='yearSelect'?'mainMenu':'title'}},document:doc};vm.createContext(box);vm.runInContext(fs.readFileSync('js/native.js','utf8'),box);await box.window.MakmalNative.init();await Promise.resolve();assert.equal(registrations,2);const press=()=>{now+=300;back();};
 for(const expected of ['unitDetail','year2','yearSelect','mainMenu','title']){press();back();assert.equal(route,expected);assert.equal(exits,0);}
 press();assert(dialog.open);press();assert(!dialog.open);press();controls['[data-stay]'].click();assert(!dialog.open);press();resume({isActive:false});assert(!dialog.open);assert.equal(stops,1);resume({isActive:true});await box.window.MakmalNative.init();assert.equal(registrations,2);press();await controls['[data-exit]'].click();assert.equal(exits,1);assert.equal(save.completedAt,'original');
 const web={window:{},document:{}};vm.createContext(web);vm.runInContext(fs.readFileSync('js/native.js','utf8'),web);await web.window.MakmalNative.init();
 const pbox={window:{},localStorage:{getItem:()=>JSON.stringify({version:'1.1.0',settings:{sound:false},profile:{name:'Aina'},progress:{year2:{animals:{mission1:save}}}}),setItem(){}}};vm.createContext(pbox);vm.runInContext(fs.readFileSync('js/progress.js','utf8'),pbox);const data=pbox.window.MakmalProgress.loadData();assert.equal(data.version,'2.4.0');assert.equal(data.settings.sound,false);assert.equal(data.progress.year2.animals.mission1.completedAt,'original');
 console.log('PASS Android Back route priority, cancel/confirm exit, single registration per event, duplicate Back guard, pause/resume cleanup, browser no-op and v1.1 migration.');
})().catch(e=>{console.error(e);process.exitCode=1;});
