const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let raw=null,blocked=false;const box={window:{},localStorage:{getItem:()=>{if(blocked)throw Error('blocked');return raw;},setItem:(k,v)=>{if(blocked)throw Error('blocked');raw=v;}}};vm.createContext(box);
for(const f of ['js/progress.js','js/content/experiments/new-units.js','js/engine/discovery.js'])vm.runInContext(fs.readFileSync(f,'utf8'),box);
const {MakmalNewContent:content,MakmalDiscovery:engine,MakmalProgress:p}=box.window;
for(const d of Object.values(content.missions))for(let run=0;run<30;run++){
 const g=engine.createSession(d);g.act('next');assert.equal(g.state.step,0);g.act('release');assert.equal(g.state.stage,0);g.act('predict',String(run%2));assert(g.canAdvance());g.act('next');assert(!g.canAdvance());g.act('hint');g.act('hint');assert(engine.hint(g.state,d).selector);
 if(d.kind==='care'){if(d.inspectFirst){g.act('provide',d.items[0].id);assert.equal(g.state.done.length,0);g.act('inspect');}for(const x of d.decoys)g.act('provide',x.id);assert.equal(g.state.done.length,0);for(const x of d.items){g.act('provide',x.id);g.act('provide',x.id);}assert.equal(g.state.done.length,d.items.length);}
 else if(['match','classify','watch','evidence','routine'].includes(d.kind)){g.act('assign',d.groups[0].id);assert.equal(Object.keys(g.state.matched).length,0);for(const x of d.items){g.act('choose',x.id);if(['watch','evidence','routine'].includes(d.kind)){g.act('assign',x.target);assert(!g.state.matched[x.id]);g.act('watch');}g.act('assign',d.groups.find(v=>v.id!==x.target).id);assert(!g.state.matched[x.id]);g.act('assign',x.target);g.act('assign',x.target);}assert.equal(Object.keys(g.state.matched).length,d.items.length);}
 else if(d.kind==='measure'){for(const x of d.items){g.act('read',String(x.length));assert(!g.state.measurements[x.id]);g.act('shift','left');g.act('shift','left');g.act('read','4');assert(!g.state.measurements[x.id]);g.act('read',String(x.length));}assert.equal(Object.keys(g.state.measurements).length,2);}
 else if(d.kind==='predictTest'){g.act('release');assert.equal(Object.keys(g.state.trials).length,0);for(const ramp of ['low','high']){g.act('ramp',ramp);g.act('release');assert(!g.state.trials[ramp]);g.act('guess',ramp==='high'?'near':'far');g.act('release');g.act('release');assert.equal(g.state.trials[ramp].result,ramp==='high'?'far':'near');assert.notEqual(g.state.trials[ramp].guess,g.state.trials[ramp].result);}assert(g.canAdvance());}
 else{g.act('classify','round');assert.equal(g.state.stage,0);g.act('inspect');g.act('classify','square');assert.equal(g.state.stage,1);g.act('classify','round');g.act('read','3');assert.equal(g.state.stage,2);g.act('shift','left');g.act('shift','left');g.act('read','3');g.act('release');assert.equal(g.state.stage,3);g.act('guess','near');g.act('release');g.act('record','near');assert.equal(g.state.stage,4);g.act('record','far');assert.equal(g.state.stage,5);}
 assert(g.canAdvance());g.act('next');g.act('next');assert.equal(g.state.step,2);for(let i=1;i<d.observations.length;i++)g.act('observe');g.act('next');g.act('think','wrong');assert(!g.canAdvance());g.act('think','correct');g.act('next');assert.equal(g.state.step,4);g.act('next');assert.equal(g.state.step,4);g.reset();assert.equal(g.state.selected,null);assert.equal(g.state.offset,2);assert.equal(g.state.stage,0);assert.equal(g.state.guess,null);assert.equal(g.state.viewed.length,0);assert.equal(Object.keys(g.state.matched).length,0);
}
const record={completed:true,attempts:7,completedAt:'2026-01-01',extra:'keep'},all=Object.fromEntries([1,2,3,4,5].map(n=>['mission'+n,record]));
for(const initial of [null,'{broken',JSON.stringify({version:'0.9.0',settings:{sound:false,extra:8},profile:{name:'Aina'},extra:'keep',progress:{year2:{electricity:all,lightDark:all,mixtures:all,plants:all,animals:{mission3:record},humans:{mission1:null},scienceSkills:'bad'}}})]){
 raw=initial;p.loadData();assert.equal(p.getData().version,'2.2.0');assert(!p.isYear2Complete());const before=JSON.stringify([p.getData().settings,p.getData().profile,p.getData().extra,p.getData().progress.year2.electricity,p.getData().progress.year2.lightDark,p.getData().progress.year2.mixtures,p.getData().progress.year2.plants]);
 for(const unit of ['animals','humans','scienceSkills'])for(let n=1;n<=5;n++){assert(p.isAvailable(n,unit));p.startMissionAttempt('mission'+n,unit);p.completeMission('mission'+n,unit);const date=p.getData().progress.year2[unit]['mission'+n].completedAt;p.startMissionAttempt('mission'+n,unit);p.completeMission('mission'+n,unit);assert.equal(p.getData().progress.year2[unit]['mission'+n].completedAt,date);}
 assert.equal(before,JSON.stringify([p.getData().settings,p.getData().profile,p.getData().extra,p.getData().progress.year2.electricity,p.getData().progress.year2.lightDark,p.getData().progress.year2.mixtures,p.getData().progress.year2.plants]));
 for(const unit of p.year2StorageUnits)for(let n=1;n<=5;n++)p.completeMission('mission'+n,unit);assert.equal(p.year2CompletedCount(),35);assert.equal(p.year2CompletedUnits(),7);assert(p.isYear2Complete());p.loadData();assert(p.isYear2Complete());
}
blocked=true;p.loadData();assert(p.isAvailable(1,'scienceSkills'));p.completeMission('mission1','scienceSkills');assert(p.isAvailable(2,'scienceSkills'));
console.log('PASS 450 new mission runs; negative guards, prediction mismatch, measurements, reset, v0.9 migration, 35-record totals and blocked storage.');
