'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const read=file=>fs.readFileSync(file,'utf8');
const box={window:{}};vm.createContext(box);
for(const file of ['js/content/experiments/electricity-mission1.js','js/content/experiments/electricity-mission2.js','js/engine/circuit.js'])vm.runInContext(read(file),box);
const def=box.window.MakmalMission2,lab=box.window.MakmalCircuit.createSession(def);
lab.state.step=1;
let html=box.window.MakmalCircuit.render(lab.state,def);
assert(html.includes('Mentol tidak menyala'));
assert(!html.includes('golden-success'));
for(const pair of def.connections)for(const terminal of pair.ends)lab.act('terminal',terminal);
assert.equal(lab.state.links.length,3);
assert(!lab.lit());
lab.act('toggle');
assert(lab.lit());
assert.equal(lab.state.message,'Hebat! Litar kamu lengkap dan mentol pun menyala!');
html=box.window.MakmalCircuit.render(lab.state,def);
for(const text of ['circuit-lit','Mentol menyala','golden-success','Bagus! Mentol menyala!','Litar lengkap membolehkan arus elektrik mengalir dan mentol menyala.'])assert(html.includes(text),text);
const experiment=read('js/engine/experiment.js'),css=read('css/circuit.css');
for(const text of ['golden-stage','golden-workspace','golden-assistant','root.dataset.mission = missionId'])assert(experiment.includes(text),text);
for(const text of ['data-mission="electricity-2"','golden-bulb-pulse','golden-rays','golden-success','@media(max-width:640px)','@media(max-height:550px)','@media(prefers-reduced-motion:reduce)'])assert(css.includes(text),text);
for(const forbidden of ['XP Saintis','Bintang Diperoleh','star-economy','reward-economy'])assert(!css.includes(forbidden),forbidden);
console.log('PASS v2.5.3 Golden Mission OFF/ON states, PICO layout, immediate science feedback, responsive treatment and reduced motion.');
