const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let raw=null;const box={window:{},localStorage:{getItem:()=>raw,setItem:(_,v)=>raw=v},Intl,Date,Math,console,CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail;}}};box.window.window=box.window;box.window.dispatchEvent=()=>{};vm.createContext(box);const run=file=>vm.runInContext(fs.readFileSync(file,'utf8'),box,{filename:file});
run('js/progress.js');
for(const file of ['js/content/experiments/new-units.js','js/content/year2.js','js/content/experiments/electricity-mission1.js','js/content/experiments/electricity-mission2.js','js/content/experiments/electricity-missions3-5.js','js/content/experiments/light-dark.js','js/content/experiments/mixtures.js','js/content/experiments/plants.js','js/content/experience.js','js/content/year3/index.js'])run(file);
for(const file of ['science-skills','lab-rules','humans','animals','plants','measurement','density','acid-alkali','solar-system','machines'])run(`js/content/year3/${file}.js`);
for(const year of [4,5,6,1]){run(`js/content/year${year}/index.js`);run(`js/content/year${year}/content.js`);}
const esc=v=>String(v??'').replace(/[&<>"']/g,''),avatar=()=>'<span class="profile-avatar">P</span>';box.window.MakmalProfiles={esc,avatar};box.window.MakmalPico={dialogue:t=>`<aside>${esc(t)}</aside>`};box.window.MakmalFeedback={emit:()=>{}};
run('js/engine/journal.js');const p=box.window.MakmalProgress,j=box.window.MakmalJournal;p.loadData();
const audit=j.audit();assert.equal(audit.total,290);assert.equal(audit.missing.length,0);assert.equal(audit.generic.length,0);assert.equal(j.all().filter(x=>x.year===1).length,50);assert.equal(j.all().filter(x=>x.year===2).length,35);assert.equal(j.all().filter(x=>x.year===3).length,50);assert.equal(j.all().filter(x=>x.year===4).length,50);assert.equal(j.all().filter(x=>x.year===5).length,50);assert.equal(j.all().filter(x=>x.year===6).length,55);
const incomplete=j.getMission(2,'electricity','electricity-1'),secret=incomplete.discovery;const hidden=j.mission(2,'electricity','electricity-1');assert(hidden.includes('Belum ditemui'));assert(!hidden.includes(secret));assert(hidden.includes('Main Misi'));
p.completeMission('mission1','electricity');const shown=j.mission(2,'electricity','electricity-1');assert(shown.includes(secret)&&shown.includes('TEMUI')&&shown.includes('Main Semula'));assert(p.isDiscoveryViewed(2,'electricity','mission1'));
const first=p.getActiveProfile().id,b=p.addProfile('B','leaf').profile.id;assert(!p.isDiscoveryViewed(2,'electricity','mission1'));p.markDiscoveryViewed(2,'electricity','mission1');assert(p.isDiscoveryViewed(2,'electricity','mission1'));p.switchProfile(first);assert(p.isDiscoveryViewed(2,'electricity','mission1'));assert.equal(p.profileStats().completed,1);p.switchProfile(b);assert.equal(p.profileStats().completed,0);assert(j.home().includes('0 / 290'));assert(j.continueMission());
raw=JSON.stringify({version:'2.2.0',settings:{sound:false},profiles:[{id:'old',name:'Lama',avatar:'pico',preferences:{viewedDiscoveries:'rosak'},progress:p.getActiveProfile().progress}],activeProfileId:'old'});p.loadData();assert.equal(p.APP_VERSION,'2.5.0');assert.equal(p.getActiveProfile().name,'Lama');assert.equal(p.isDiscoveryViewed(2,'electricity','mission1'),false);assert.equal(j.audit().total,290);
for(const item of j.all()){if(item.year===2)p.completeMission(item.progressKey,item.storageUnit);else p.forYear(item.year).completeMission(item.progressKey,item.storageUnit);}
assert.equal(p.profileStats().completed,290);const full=j.home();assert(full.includes('BUKU MAKMAL LENGKAP!')&&full.includes('6 / 6 tahun')&&full.includes('58 / 58 unit')&&full.includes('290 / 290 eksperimen'));
console.log('PASS 290 canonical discoveries, no leakage, recent/continue foundations, viewed state, profile isolation and v2.2 migration.');
