const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const progressCode=fs.readFileSync('js/progress.js','utf8'),profilesCode=fs.readFileSync('js/engine/profiles.js','utf8');
const record={completed:true,attempts:3,completedAt:'2026-01-02T03:04:05.000Z'};
const legacyProgress={year1:{'science-skills':{mission1:record}},year2:{electricity:{mission1:record}},year3:{},year4:{},year5:{},year6:{}};
let raw=JSON.stringify({version:'2.0.0',settings:{sound:false,deviceField:'keep'},profile:{name:'Aina'},progress:legacyProgress,unknown:{keep:true}});
const storage={getItem:()=>raw,setItem:(_,value)=>{raw=value;}};
const box={window:{},localStorage:storage,Intl,Date,Math};vm.createContext(box);vm.runInContext(progressCode,box);const p=box.window.MakmalProgress;
p.loadData();assert.equal(p.APP_VERSION,'2.4.0');assert.equal(p.getProfiles().length,1);assert.equal(p.getActiveProfile().name,'Aina');assert.equal(p.getData().settings.sound,false);assert.equal(p.getData().settings.deviceField,'keep');assert.equal(p.getData().unknown.keep,true);assert(p.isMissionComplete('mission1','electricity'));assert.equal(p.forYear(1).isMissionComplete('mission1','science-skills'),true);assert.equal(p.getData().progress.year2.electricity.mission1.completedAt,record.completedAt);
const first=p.getActiveProfile().id;assert.equal(p.addProfile('  <Sofia>  ','leaf').profile.name,'Sofia');const second=p.getActiveProfile().id;assert.notEqual(first,second);assert.equal(p.isMissionComplete('mission1','electricity'),false);p.completeMission('mission1','electricity');assert.equal(p.profileStats(second).completed,1);p.switchProfile(first);assert.equal(p.isMissionComplete('mission1','electricity'),true);assert.equal(p.profileStats(first).completed,2);assert.equal(p.profileStats(second).completed,1);
assert(p.updateProfile(second,{name:' Ayyash   Cilik ',avatar:'planet'}).ok);assert.equal(p.getProfiles().find(x=>x.id===second).name,'Ayyash Cilik');assert.equal(p.getProfiles().find(x=>x.id===second).avatar,'planet');assert.equal(p.updateProfile(second,{name:' <> '}).ok,false);
for(const name of ['B','C','D','E'])assert(p.addProfile(name,'flask').ok);assert.equal(p.getProfiles().length,6);assert.equal(p.addProfile('G').ok,false);
const active=p.getData().activeProfileId;assert(p.deleteProfile(active).ok);assert.equal(p.getProfiles().length,5);assert.notEqual(p.getData().activeProfileId,active);while(p.getProfiles().length>1)assert(p.deleteProfile(p.getProfiles().at(-1).id).ok);assert.equal(p.deleteProfile(p.getActiveProfile().id).ok,false);
// Exact master completion belongs to one profile only.
const all=Object.fromEntries([1,2,3,4,5].map(n=>['mission'+n,{...record}]));const full={year1:Object.fromEntries(p.year1Units.map(u=>[u,all])),year2:Object.fromEntries(p.year2StorageUnits.map(u=>[u,all])),year3:Object.fromEntries(p.year3Units.map(u=>[u,all])),year4:Object.fromEntries(p.year4Units.map(u=>[u,all])),year5:Object.fromEntries(p.year5Units.map(u=>[u,all])),year6:Object.fromEntries(p.year6Units.map(u=>[u,all]))};p.saveData({...p.getData(),progress:full});const fullId=p.getActiveProfile().id;assert.equal(p.profileStats(fullId).completed,290);assert(p.allYearsComplete());const empty=p.addProfile('Kosong').profile.id;assert.equal(p.profileStats(empty).completed,0);assert(!p.allYearsComplete());p.switchProfile(fullId);assert(p.allYearsComplete());p.switchProfile(empty);assert(p.resetProfile(empty));assert.equal(p.profileStats(empty).attempts,0);assert.equal(p.profileStats(fullId).completed,290);
// Missing/deleted active id recovers without erasing profiles.
const parsed=JSON.parse(raw);parsed.activeProfileId='missing';raw=JSON.stringify(parsed);p.loadData();assert(p.getActiveProfile());assert.equal(p.getProfiles().length,2);
// Malformed and blocked storage recover in memory.
raw='{bad';p.loadData();assert.equal(p.getProfiles().length,1);const blocked={getItem:()=>null,setItem:()=>{throw Error('blocked')}};const blockedBox={window:{},localStorage:blocked,Intl,Date,Math};vm.createContext(blockedBox);vm.runInContext(progressCode,blockedBox);assert.doesNotThrow(()=>{const q=blockedBox.window.MakmalProgress;q.loadData();q.addProfile('Lokal');q.completeMission();});
vm.runInContext(profilesCode,box);const ui=box.window.MakmalProfiles;assert(ui.select().includes('PILIH PEMAIN'));assert(ui.gate().includes('Tahan untuk masuk'));assert(ui.support().includes('RM4.90')&&ui.support().includes('RM9.90')&&ui.support().includes('RM19.90'));assert(ui.support().includes('tidak membuka kandungan tambahan'));assert(ui.dashboard().includes('RUANG IBU BAPA / PENJAGA'));
console.log('PASS v2.0 migration, 6-profile limit, validation, switching, isolation, master completion, deletion, reset, malformed/missing/blocked storage and parent/support UI.');
