'use strict';
const output=document.getElementById('results'),assert=(v,m)=>{if(!v)throw Error(m);};
document.getElementById('run').onclick=async()=>{
 const run=document.getElementById('run');run.disabled=true;output.textContent='';let total=0;
 const record={completed:true,attempts:3,completedAt:'2026-01-01T00:00:00Z',extra:8},all=Object.fromEntries([1,2,3,4,5].map(n=>['mission'+n,record]));
 try{
  const html=await(await fetch('../index.html')).text();for(const url of ['animals/rabbit.webp','animals/animals.svg','humans/senses.svg'])assert((await fetch('../assets/experiments/'+url)).ok,'Missing asset '+url);
  for(const [width,height] of [[1366,768],[1920,1080],[390,844],[360,640],[800,450]])for(const unit of ['animals','humans','science-skills'])for(const scenario of ['fresh','v0.9','partial','unit-complete','all-complete','malformed','bad-records','blocked']){
   const storage=unit==='science-skills'?'scienceSkills':unit;
   const year2={electricity:all,lightDark:all,mixtures:all,plants:all,animals:{},humans:{},scienceSkills:{},future:{keep:9}};
   year2[storage]=scenario==='partial'?{mission3:record}:scenario==='unit-complete'?all:scenario==='bad-records'?{mission1:null,mission2:'bad',mission3:{attempts:-2}}:{};
   if(scenario==='all-complete')for(const id of ['animals','humans','scienceSkills'])year2[id]=all;
   const raw=scenario==='malformed'?'{bad':['fresh','blocked'].includes(scenario)?null:JSON.stringify({version:'0.9.0',settings:{sound:false},profile:{name:'Aina'},extra:7,progress:{year2}});
   const frame=document.createElement('iframe');frame.style.width=width+'px';frame.style.height=height+'px';
   const boot=`<base href="../"><script>window.qaErrors=[];addEventListener('error',e=>{if(e.message)qaErrors.push(e.message)});addEventListener('unhandledrejection',e=>qaErrors.push(String(e.reason)));let raw=${JSON.stringify(raw)};Object.defineProperty(window,'localStorage',{value:{getItem:()=>{${scenario==='blocked'?"throw Error('blocked')":'return raw'}},setItem:(k,v)=>{${scenario==='blocked'?"throw Error('blocked')":'raw=v'}}}});<\/script>`;
   frame.srcdoc=html.replace('<head>','<head>'+boot);document.getElementById('frame').replaceChildren(frame);await new Promise(r=>frame.onload=r);
   const w=frame.contentWindow,d=frame.contentDocument,p=w.MakmalProgress,polish=window.installPolishChecks(w,d);let completions=0;const complete=p.completeMission;p.completeMission=(...args)=>{completions++;return complete(...args);};
   const preserved=()=>JSON.stringify([p.getData().settings,p.getData().profile,p.getData().extra,Object.fromEntries(Object.entries(p.getData().progress.year2).filter(([id])=>id!==storage))]);const before=preserved();
   const click=sel=>{const e=d.querySelector(sel);assert(e&&!e.disabled,'Unavailable '+sel);e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect(),hit=d.elementFromPoint(r.x+r.width/2,r.y+r.height/2);assert(hit&&(e===hit||e.contains(hit)),'Intercepted '+sel);for(const type of ['pointerdown','pointerup'])e.dispatchEvent(new w.PointerEvent(type,{bubbles:true,pointerType:'touch',pointerId:12,button:0}));polish.click(sel,()=>e.click());};
   const check=phase=>{polish.check();assert(d.documentElement.scrollWidth<=width,'Overflow '+phase);for(const e of d.querySelectorAll('button,h1,h2,h3,p,.learning-steps'))assert(e.scrollWidth<=e.clientWidth+2&&e.scrollHeight<=e.clientHeight+2,'Clipped '+phase+' '+e.textContent);for(const e of d.querySelectorAll('button'))assert(e.getBoundingClientRect().height>=44,'Small target '+phase);assert(w.qaErrors.length===0,w.qaErrors.join(';'));};
   check('Title');click('[data-route="mainMenu"]');check('Menu');click('[data-route="yearSelect"]');check('Years');click('[data-route="year2"]');check('Year2');assert(d.querySelectorAll('[data-unit]').length===7,'Unit count');assert(d.querySelector('.year-progress').textContent.includes(p.year2CompletedCount()+' / 35'),'Total mismatch');click(`[data-unit="${unit}"]`);assert(p.isAvailable(1,storage),'Mission1 trapped');
   if(!p.isYear2Complete()){w.MakmalRouter.navigate('year2Complete');assert(!d.querySelector('.year-finale'),'Premature finale');click(`[data-unit="${unit}"]`);}
   for(let n=1;n<=5;n++){
    assert(p.isAvailable(n,storage),'Unlock '+n);const def=w.MakmalNewContent.missions[unit+'-'+n];click(`[data-mission="${unit}-${n}"]`);if(d.querySelector('[data-exp="start"]'))click('[data-exp="start"]');const attempts=p.getData().progress.year2[storage]['mission'+n].attempts;let firstDate=p.getData().progress.year2[storage]['mission'+n].completedAt;
    for(let repeat=0;repeat<2;repeat++){
     check('Ramal');click('[data-exp="predict"][data-value="1"]');click('[data-exp="next"]');check('Cuba');click('[data-exp="hint"]');assert(!d.querySelector('.hint-target'),'Hint1 reveals target');click('[data-exp="hint"]');assert(d.querySelector('.hint-target'),'Hint2 missing target');click('[data-exp="hint"]');
     if(def.kind==='care'){if(def.inspectFirst){assert(d.querySelector('[data-exp="provide"]').disabled,'Inspect bypass');click('[data-exp="inspect"]');}for(const x of def.decoys)click(`[data-exp="provide"][data-value="${x.id}"]`);for(const x of def.items)click(`[data-exp="provide"][data-value="${x.id}"]`);assert(d.querySelector('.care-complete'),'Care feedback missing');}
     else if(['match','classify','watch','evidence','routine'].includes(def.kind)){for(const x of def.items){click(`[data-exp="choose"][data-value="${x.id}"]`);if(['watch','evidence','routine'].includes(def.kind)){assert(d.querySelector('[data-exp="assign"]').disabled,'Observation bypass');click('[data-exp="watch"]');}click(`[data-exp="assign"][data-value="${def.groups.find(g=>g.id!==x.target).id}"]`);assert(!d.querySelector(`[data-exp="choose"][data-value="${x.id}"]`).disabled,'Wrong accepted');click(`[data-exp="assign"][data-value="${x.target}"]`);}}
     else if(def.kind==='measure'){for(const x of def.items){click(`[data-exp="read"][data-value="${x.length}"]`);assert(d.querySelector('[data-exp="next"]').disabled,'Zero not required');click('[data-exp="shift"][data-value="left"]');click('[data-exp="shift"][data-value="left"]');click(`[data-exp="read"][data-value="${x.length}"]`);}}
     else if(def.kind==='predictTest'){for(const ramp of ['low','high']){click(`[data-exp="ramp"][data-value="${ramp}"]`);assert(d.querySelector('[data-exp="release"]').disabled,'Prediction missing');click(`[data-exp="guess"][data-value="${ramp==='high'?'near':'far'}"]`);click('[data-exp="release"]');}assert(d.querySelector('.trial-records').textContent.includes('Hasil'),'No comparison');}
     else{click('[data-exp="inspect"]');click('[data-exp="classify"][data-value="round"]');click('[data-exp="shift"][data-value="left"]');click('[data-exp="shift"][data-value="left"]');click('[data-exp="read"][data-value="3"]');click('[data-exp="guess"][data-value="near"]');click('[data-exp="release"]');click('[data-exp="record"][data-value="far"]');}
     check('Solved');click('[data-exp="next"]');check('Perhati');while(d.querySelector('[data-exp="observe"]'))click('[data-exp="observe"]');click('[data-exp="next"]');check('Fikir');click('[data-exp="think"][data-value="wrong"]');assert(d.querySelector('[data-exp="next"]').disabled,'Wrong reflection accepted');click('[data-exp="think"][data-value="correct"]');click('[data-exp="next"]');check('Temui');
     assert(completions===(n-1)*2+repeat+1,'Duplicate completion');const record=p.getData().progress.year2[storage]['mission'+n];assert(record.completed&&record.attempts===attempts+repeat,'Attempt error');if(firstDate)assert(record.completedAt===firstDate,'Timestamp lost');firstDate=record.completedAt;assert(preserved()===before,'Other data overwritten');if(!repeat)click('[data-exp="restart"]');total++;
    }
    click('[data-exp="exit"]');check('Unit hub');
   }
   assert(p.isUnitComplete(storage),'Unit incomplete');for(let n=1;n<=5;n++){click(`[data-mission="${unit}-${n}"]`);click('[data-exp="start"]');click('[data-exp="predict"][data-value="0"]');click('[data-exp="next"]');click('[data-exp="hint"]');click('[data-exp="hint"]');click('[data-exp="restart"]');assert(!d.querySelector('.hint-target'),'Stale hint');click('[data-action="back"]');click(`[data-mission="${unit}-${n}"]`);click('[data-exp="start"]');click('[data-action="home"]');click('[data-route="yearSelect"]');click('[data-route="year2"]');click(`[data-unit="${unit}"]`);}
   click('[data-action="back"]');assert(d.querySelector('.year-progress').textContent.includes(p.year2CompletedCount()+' / 35'),'Final total mismatch');if(p.isYear2Complete()){click('[data-route="year2Complete"]');check('Year finale');assert(d.querySelector('.year-finale').textContent.includes('35 / 35'),'Finale total');click('[data-route="year2"]');assert(d.querySelectorAll('[data-unit]').length===7,'Finale exit');}
   if(scenario!=='blocked'){p.loadData();assert(p.isUnitComplete(storage),'Reload lost completion');}assert(preserved()===before,'Navigation changed old data');assert(!w.qaErrors.length,w.qaErrors.join(';'));
   output.textContent+=`PASS ${width}×${height} ${unit} ${scenario}: five missions twice; controls, replay, hints, totals, storage and layout.\n`;
  }
  output.textContent+=`ALL 120 SCENARIOS PASSED · ${total} MISSION COMPLETIONS`;
 }catch(e){output.textContent+='FAIL '+e.message;}finally{run.disabled=false;}
};
