'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const read=file=>fs.readFileSync(file,'utf8');
const index=read('index.html'),css=read('css/release-polish.css'),app=read('js/app.js'),profiles=read('js/engine/profiles.js'),router=read('js/router.js');
assert(index.includes('<meta name="app-version" content="2.5.1">'));
assert(index.includes('css/release-polish.css?v=2.5.1'));
for(const key of ['--mc-blue','--mc-blue-dark','--mc-yellow','--mc-bg','--mc-surface','--mc-border','--mc-text','--mc-muted','--mc-success','--mc-warning','--mc-radius','--mc-shadow','--mc-control','--mc-focus'])assert(css.includes(key),key);
assert(css.includes('@media(prefers-reduced-motion:reduce)'));
assert(css.includes('@media(max-width:640px)'));
assert(css.includes('@media(max-height:550px) and (min-width:641px)'));
assert(css.includes('@media(min-width:1500px)'));
for(const selector of ['.experiment-title::before','.learning-steps li:nth-child(5)','.pico-dialogue::before','.workbench::before','.completion::before','@media(min-width:1100px)'])assert(css.includes(selector),selector);
for(const forbidden of ['XP Saintis','Bintang Diperoleh','star-economy','reward-economy'])assert(!css.includes(forbidden),forbidden);
assert(app.includes('year-progress-copy'));
assert(app.includes("item.completed===item.total?'✓ Selesai'"));
assert(app.includes('aria-label="Tahun ${item.year}, ${item.completed} daripada ${item.total} eksperimen'));
assert(profiles.includes('current-profile'));
assert(profiles.includes('aria-current="true"'));
assert.equal((app.match(/autofocus>Batal/g)||[]).length,2);
assert(router.includes("screen.querySelector('[autofocus]')"));
assert(router.includes('(preferred||screen).focus'));
const box={window:{}};vm.createContext(box);vm.runInContext(read('js/progress.js'),box);assert.equal(box.window.MakmalProgress.APP_VERSION,'2.5.1');
console.log('PASS v2.5.1 visual-target alignment, design tokens, responsive mission polish, explicit states, safe dialog focus and release markers.');
