'use strict';
document.getElementById('run').onclick=async()=>{
 const run=document.getElementById('run'),out=document.getElementById('results');run.disabled=true;out.textContent='';let scenarios=0,total=0;
 const assert=(v,m)=>{if(!v)throw Error(m);},old={completed:true,attempts:3,completedAt:'2026-01-01',extra:7},all=Object.fromEntries([1,2,3,4,5].map(n=>['mission'+n,old]));
 try{const html=await(await fetch('../index.html')).text(),quick=new URLSearchParams(location.search).has('quick');for(const [width,height] of [[1366,768],[1920,1080],[390,844],[360,640],[800,450]])for(const scenario of (quick?['fresh']:['fresh','legacy','partial','unit','full','malformed','blocked','bad-records'])){
 const year2={electricity:all,animals:all,plants:{keep:9}},year3={humans:all,machines:{keep:6}},ids=['science-skills','humans','animals','plants','light-properties','sound','energy','materials','earth','machines'];
 const year4=scenario==='full'?Object.fromEntries(ids.map(id=>[id,all])):scenario==='unit'?{humans:all}:scenario==='partial'?{humans:{mission3:old}}:scenario==='bad-records'?{humans:{mission1:null,mission2:'bad',mission3:{attempts:-8}}}:{};
 const raw=scenario==='malformed'?'{bad':scenario==='fresh'?null:JSON.stringify({version:'1.3.0',settings:{sound:false},profile:{name:'Aina'},extra:8,progress:{year2,year3,year4}});
 const frame=document.createElement('iframe');frame.style.width=width+'px';frame.style.height=height+'px';const boot=`<base href="../"><script>window.qaErrors=[];addEventListener('error',e=>{if(e.message)qaErrors.push(e.message)});addEventListener('unhandledrejection',e=>qaErrors.push(String(e.reason)));let raw=${JSON.stringify(raw)};Object.defineProperty(window,'localStorage',{value:{getItem:()=>{${scenario==='blocked'?"throw Error('blocked')":'return raw'}},setItem:(k,v)=>{${scenario==='blocked'?"throw Error('blocked')":'raw=v'}}}});<\/script>`;
 frame.srcdoc=html.replace('<head>','<head>'+boot);document.getElementById('frame').replaceChildren(frame);await new Promise(r=>frame.onload=r);
 const w=frame.contentWindow,d=frame.contentDocument,p=w.MakmalProgress,y=p.forYear(4);let session,completed=0,events=0;const create=w.MakmalYear4Lab.createSession;w.MakmalYear4Lab.createSession=def=>(session=create(def));const forYear=p.forYear;p.forYear=n=>{const scope=forYear(n),complete=scope.completeMission;scope.completeMission=(...a)=>{completed++;return complete(...a);};return scope;};const play=w.MakmalRewards.play;w.MakmalRewards.play=e=>{events++;return play(e);};
 const preserve=()=>JSON.stringify([p.getData().progress.year2,p.getData().progress.year3,p.getData().settings,p.getData().profile,p.getData().extra]);const before=preserve();
 const check=phase=>{assert(d.documentElement.scrollWidth<=width,'Overflow '+phase);for(const e of d.querySelectorAll('button,h1,h2,h3,p,.learning-steps')){assert(e.scrollWidth<=e.clientWidth+2,'Clipped width '+phase+' '+e.textContent);assert(e.scrollHeight<=e.clientHeight+2,'Clipped height '+phase+' '+e.textContent);}for(const e of d.querySelectorAll('button'))if(e.getClientRects().length)assert(e.getBoundingClientRect().height>=44,'Small target '+e.textContent);assert(!w.qaErrors.length,w.qaErrors.join(';'));};
 const click=sel=>{const e=d.querySelector(sel);assert(e&&!e.disabled,'Unavailable '+sel);e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect(),hit=d.elementFromPoint(r.x+r.width/2,r.y+r.height/2);assert(hit&&(e===hit||e.contains(hit)),'Intercepted '+sel);const prior=events;for(const type of ['pointerdown','pointerup'])e.dispatchEvent(new w.PointerEvent(type,{bubbles:true,pointerType:'touch',pointerId:6,button:0}));e.click();assert(events-prior<=1,'Duplicate audio '+sel);};
 check('Title');click('[data-route="mainMenu"]');check('Menu');click('[data-route="yearSelect"]');check('Years');assert(d.querySelector('[data-route="year2"]')&&d.querySelector('[data-route="year4"]'),'Active years');click('[data-route="year4"]');check('Year4');assert(d.querySelectorAll('[data-y4unit]').length===10,'Unit count');
 if(!y.isYearComplete()){w.MakmalRouter.navigate('year4Complete');assert(w.MakmalRouter.currentScreen()==='year4','Premature finale');}
 for(const unit of w.MakmalYear4.units){click(`[data-y4unit="${unit.id}"]`);assert(d.querySelectorAll('[data-y4mission]').length===5,'Mission count');assert(y.isAvailable(1,unit.id),'Mission 1 locked');check('Unit');
 for(const m of unit.missions){assert(y.isAvailable(m.number,unit.id),'Unlock '+m.id);const def=w.MakmalYear4.missions[m.id];click(`[data-y4mission="${m.id}"]`);if(d.querySelector('[data-exp="start"]'))click('[data-exp="start"]');const attempt=p.getData().progress.year4[unit.id][def.progressKey].attempts;let date=p.getData().progress.year4[unit.id][def.progressKey].completedAt;
 for(let replay=0;replay<2;replay++){
  check(m.id+' Ramal');assert(d.querySelector('[data-exp="next"]').disabled,'Prediction bypass');click('[data-exp="predict"][data-value="1"]');click('[data-exp="next"]');check(m.id+' Cuba');
  click('[data-exp="hint"]');click('[data-exp="hint"]');assert(d.querySelector('.hint-target'),'Hint target absent '+m.id);click('[data-exp="hint"]');
  let guard=0;while(!session.canAdvance()){const [action,value]=w.MakmalYear4Domains[def.mode].hint(session.state,def);const selector=`[data-exp="${action}"]${value===undefined?'':`[data-value="${value}"]`}`;click(selector);assert(++guard<100,'Stuck '+m.id);check(m.id+' action '+action);}
  click('[data-exp="next"]');check('Perhati');while(d.querySelector('[data-exp="observe"]'))click('[data-exp="observe"]');click('[data-exp="next"]');click('[data-exp="think"][data-value="wrong"]');assert(d.querySelector('[data-exp="next"]').disabled,'Wrong reflection bypass');click('[data-exp="think"][data-value="correct"]');click('[data-exp="next"]');check('Temui');total++;
  const record=p.getData().progress.year4[unit.id][def.progressKey];assert(record.completed&&record.attempts===attempt+replay,'Attempt count');if(date)assert(record.completedAt===date,'Date overwritten');date=record.completedAt;assert(preserve()===before,'Earlier years/settings changed');if(!replay)click('[data-exp="restart"]');
 }
 await new Promise(r=>setTimeout(r,0));click('[data-exp="exit"]');assert(w.MakmalRouter.currentScreen()==='year4Unit','Mission exit');check('Mission list');
 }
 assert(y.isUnitComplete(unit.id),'Unit incomplete');click('[data-action="back"]');assert(w.MakmalRouter.currentScreen()==='year4','Unit Back');assert(d.querySelector('.year-progress').textContent.includes(y.completedTotal()+' / 50'),'Counter');scenarios++;
 out.textContent+=`PASS ${width}×${height} ${scenario} ${unit.id}: 5 missions twice, navigation, targets, hints, records, no overflow/errors.\n`;
 }
 assert(completed===100,'Duplicate completion writes');assert(y.completedTotal()===50&&y.completedUnits()===10,'Year counters');click('[data-route="year4Complete"]');check('Year finale');assert(d.querySelector('.year-finale').textContent.includes('50 / 50'),'Finale');click('[data-route="year4"]');click('[data-action="back"]');assert(w.MakmalRouter.currentScreen()==='yearSelect','Year Back');click('[data-action="home"]');assert(w.MakmalRouter.currentScreen()==='mainMenu','Home');if(scenario!=='blocked'){p.loadData();assert(y.completedTotal()===50,'Reload lost Year 4');}assert(preserve()===before,'Reload changed Year 2');assert(!w.qaErrors.length,'Errors');
 }out.textContent+=`ALL ${scenarios} UNIT SCENARIOS PASSED · ${total} MISSION COMPLETIONS`;}
 catch(e){out.textContent+='FAIL '+e.message;}finally{run.disabled=false;}
};
