'use strict';
(()=>{const Y=window.MakmalYear4;
 const u=(id,title,icon,description,missions)=>Y.addUnit({id,title,icon,description,totalMissions:5},missions);
 const q=(title,domain,mode,objective,instruction,discovery,actions,scene)=>({title,domain,mode,objective,instruction,discovery,scene,observations:[discovery,'Bukti pada model menyokong penemuan ini.'],question:'Apakah kesimpulan yang disokong oleh penyiasatan?',answers:[discovery,'Ramalan awal sentiasa mesti betul.'],actions});
 const seq=(...x)=>x.map(([id,label,note,art])=>({id,label,note,art}));
 const cls=(...x)=>x.map(([id,label,target,note,art])=>({id,label,target,note,art}));
 u('science-skills','Kemahiran Saintifik','🔬','Rancang penyiasatan dengan bukti dan pemboleh ubah.',[
  q('Perhati Dengan Teliti','evidence','compare','Bezakan pemerhatian daripada inferens.','Periksa tiga bukti sebelum mengelaskannya.','Pemerhatian menerangkan perkara yang dilihat atau diukur; inferens menerangkan kemungkinan sebab.',cls(['warna','Daun hijau','observe','Warna dilihat secara langsung.','🍃'],['panjang','Batang 8 cm','observe','Panjang diukur dengan pembaris.','📏'],['subur','Pokok subur kerana baja','infer','Sebab itu ialah inferens yang boleh diuji.','🌱']),'🔎'),
  q('Cari Pemboleh Ubah','variables','classify','Kenal pasti tiga jenis pemboleh ubah.','Padankan cahaya, tinggi pokok dan air dengan peranannya.','Pemboleh ubah dimanipulasikan diubah, pemboleh ubah bergerak balas diukur dan pemboleh ubah dimalarkan dikekalkan.',cls(['light','Tempoh cahaya','manipulated','Saintis mengubah tempoh cahaya.','☀️'],['height','Tinggi pokok','responding','Tinggi pokok diukur.','📏'],['water','Jumlah air','controlled','Jumlah air dikekalkan sama.','💧']),'🧪'),
  q('Bina Hipotesis','design','select','Pilih hipotesis yang boleh diuji.','Periksa hubungan cahaya dengan pertumbuhan lalu pilih pernyataan boleh diuji.','Hipotesis menghubungkan pemboleh ubah yang diubah dengan hasil yang boleh diukur.',cls(['testable','Jika tempoh cahaya bertambah, tinggi pokok mungkin bertambah.','yes','Dua pemboleh ubah boleh diuji dan diukur.','✅'],['opinion','Pokok ini paling cantik.','no','Cantik ialah pendapat, bukan ukuran penyiasatan.','💭'],['vague','Pokok akan berubah.','no','Pernyataan ini tidak menyatakan ukuran yang jelas.','❓']),'🌱'),
  q('Uji Dengan Adil','fair-test','checklist','Sediakan ujian adil bagi dua pokok.','Tetapkan pasu, air dan jenis pokok sama; ubah cahaya sahaja.','Ujian adil mengubah satu pemboleh ubah sambil mengekalkan pemboleh ubah lain.',seq(['same-plant','Pilih jenis pokok sama','Kedua-dua pokok jenis sama.','🌿'],['same-water','Samakan jumlah air','Air dikawal.','💧'],['change-light','Ubah tempoh cahaya sahaja','Hanya cahaya dimanipulasikan.','☀️'],['measure','Ukur tinggi selepas seminggu maya','Hasil diukur dengan cara sama.','📏']),'⚖️'),
  q('Penyiasatan Saintis','inquiry','sequence','Gabungkan ramalan, kawalan, ujian dan kesimpulan.','Susun dan jalankan penyiasatan landasan bola.','Kesimpulan dibuat daripada keputusan ujian terkawal, walaupun ramalan awal berbeza.',seq(['predict-test','Ramal landasan mana lebih jauh','Ramalan direkod tanpa markah.','💭'],['control-ball','Gunakan bola yang sama','Jenis bola dikawal.','⚽'],['test-both','Uji kedua-dua landasan','Dua ujian dijalankan dengan cara sama.','📐'],['measure-distance','Ukur jarak gerakan','Jarak menjadi bukti.','📏'],['conclude','Buat kesimpulan daripada rekod','Kesimpulan merujuk hasil sebenar.','📝']),'📊')
 ]);
 u('humans','Manusia','🫁','Terokai pernafasan melalui model selamat.',[
  q('Laluan Udara','breathing','sequence','Susun laluan udara semasa menarik nafas.','Pilih organ mengikut laluan udara ke peparu.','Udara masuk melalui hidung, bergerak melalui trakea dan sampai ke peparu.',seq(['nose','Hidung','Udara ditapis dan dilembapkan.','👃'],['trachea','Trakea','Salur membawa udara.','↕️'],['lungs','Peparu','Pertukaran gas berlaku di peparu pada aras asas.','🫁']),'🫁'),
  q('Tarik dan Hembus Nafas','breathing','compare','Bandingkan model menarik dan menghembus nafas.','Uji kedua-dua keadaan dan perhatikan dada.','Semasa menarik nafas dada mengembang; semasa menghembus nafas dada mengecil.',seq(['inhale','Tarik nafas','Dada model mengembang dan udara masuk.','⬆️'],['exhale','Hembus nafas','Dada model mengecil dan udara keluar.','⬇️']),'🫁'),
  q('Oksigen dan Karbon Dioksida','breathing','classify','Bandingkan udara sedutan dan hembusan secara kualitatif.','Kelaskan gas yang relatif lebih banyak dalam dua aliran udara.','Udara sedutan mempunyai lebih oksigen, manakala udara hembusan mempunyai lebih karbon dioksida berbanding sedutan.',cls(['oxygen','Oksigen relatif lebih banyak','inhale','Bandingkan udara masuk dengan udara keluar.','O₂'],['carbon','Karbon dioksida relatif lebih banyak','exhale','Badan menghasilkan karbon dioksida.','CO₂']),'💨'),
  q('Kadar Pernafasan','breathing-rate','compare','Bandingkan kadar pernafasan rehat dan selepas aktiviti maya.','Kira model selama masa yang sama bagi kedua-dua keadaan.','Kadar pernafasan biasanya meningkat selepas aktiviti kerana badan memerlukan lebih oksigen.',seq(['rest','Kira ketika rehat','Model mencatat 16 nafas seminit.','🪑'],['activity','Jalankan aktiviti maya','Aktiviti meningkatkan keperluan tenaga.','🏃'],['count','Kira selepas aktiviti','Model mencatat 28 nafas seminit.','⏱️']),'⏱️'),
  q('Cabaran Sistem Pernafasan','breathing','sequence','Baiki model pernafasan berdasarkan bukti.','Susun laluan, uji dada dan bandingkan gas.','Sistem pernafasan membawa udara masuk dan keluar; kadar pernafasan berubah mengikut aktiviti.',seq(['path','Lengkapkan laluan udara','Hidung → trakea → peparu.','🫁'],['inhale','Uji tarikan nafas','Dada mengembang.','⬆️'],['exhale','Uji hembusan','Dada mengecil.','⬇️'],['compare','Bandingkan rekod gas dan kadar','Bukti digabungkan.','📊']),'🧑‍🔬')
 ]);
 u('animals','Haiwan','🐾','Bandingkan organ pernafasan dan kumpulan vertebrata.',[
  q('Organ Pernafasan Haiwan','animals','compare','Periksa empat model organ pernafasan.','Uji ikan, mamalia, serangga dan cacing.','Haiwan yang berbeza boleh bernafas menggunakan insang, peparu, spirakel atau kulit lembap.',seq(['fish','Periksa ikan','Ikan menggunakan insang.','🐟'],['cat','Periksa kucing','Kucing menggunakan peparu.','🐈'],['grasshopper','Periksa belalang','Belalang bernafas melalui spirakel yang bersambung dengan sistem trakea.','🦗'],['worm','Periksa cacing','Cacing bernafas melalui kulit lembap.','🪱']),'🐾'),
  q('Siapa Bernafas Dengan Apa?','animals','classify','Padankan haiwan dengan organ pernafasannya.','Periksa ciri habitat sebelum memadankan.','Organ pernafasan haiwan sesuai dengan cara hidupnya.',cls(['fish','Ikan','gills','Hidup di air; insang mengambil oksigen terlarut.','🐟'],['whale','Paus','lungs','Paus naik ke permukaan untuk bernafas.','🐋'],['grasshopper','Belalang','spiracles','Spirakel ialah bukaan pada badan serangga.','🦗'],['worm','Cacing','skin','Kulit perlu lembap untuk pertukaran gas.','🪱']),'🫧'),
  q('Vertebrata atau Bukan?','animals','classify','Kelaskan haiwan berdasarkan tulang belakang.','Periksa rangka atau struktur badan setiap haiwan.','Vertebrata mempunyai tulang belakang; invertebrata tidak mempunyainya.',cls(['cat','Kucing','vertebrate','Rangka menunjukkan tulang belakang.','🐈'],['fish','Ikan','vertebrate','Ikan juga mempunyai tulang belakang.','🐟'],['butterfly','Rama-rama','invertebrate','Serangga tiada tulang belakang.','🦋'],['snail','Siput','invertebrate','Siput tiada tulang belakang.','🐌']),'🦴'),
  q('Kelas Vertebrata','animals','classify','Kelaskan contoh vertebrata secara ringkas.','Gunakan litupan badan, pembiakan dan habitat sebagai bukti.','Vertebrata boleh dikelaskan sebagai mamalia, burung, reptilia, amfibia atau ikan.',cls(['cat','Kucing','mammal','Berbulu dan menyusukan anak.','🐈'],['eagle','Helang','bird','Berbulu pelepah dan bertelur.','🦅'],['turtle','Kura-kura','reptile','Bersisik dan bertelur.','🐢'],['frog','Katak','amphibian','Hidup di air dan darat.','🐸'],['fish','Ikan','fish','Bersisik, bersirip dan hidup di air.','🐟']),'🧬'),
  q('Cabaran Dunia Haiwan','animals','sequence','Gunakan beberapa ciri untuk mengenal haiwan misteri.','Periksa tulang belakang, litupan badan dan organ pernafasan.','Pengelasan haiwan perlu berdasarkan beberapa bukti, bukan rupa sahaja.',seq(['backbone','Periksa tulang belakang','Ada tulang belakang.','🦴'],['cover','Periksa litupan badan','Kulit lembap.','🔎'],['breath','Periksa organ pernafasan','Peparu ketika dewasa dan kulit lembap membantu pernafasan.','🫁'],['identify','Kenal pasti amfibia','Bukti sepadan dengan katak.','🐸']),'🐸')
 ]);
 u('plants','Tumbuhan','🌻','Siasat gerak balas tumbuhan dan fotosintesis asas.',[
  q('Tumbuhan Bertindak Balas','plant-response','compare','Uji gerak balas pucuk dan akar terhadap rangsangan.','Dedahkan model kepada cahaya, air dan graviti.','Bahagian tumbuhan bergerak balas terhadap rangsangan seperti cahaya, air dan graviti.',seq(['light','Letak cahaya di sisi','Pucuk membengkok ke arah cahaya.','☀️'],['water','Letak air di sisi tanah','Akar tumbuh ke arah air.','💧'],['gravity','Pusing pasu maya','Akar terus tumbuh mengikut arah tarikan graviti.','🌍']),'🌱'),
  q('Arah Cahaya','plant-response','compare','Bandingkan pucuk dengan cahaya kiri dan kanan.','Ubah kedudukan lampu dan perhatikan pucuk.','Pucuk tumbuh ke arah sumber cahaya.',seq(['left','Letak cahaya di kiri','Pucuk membengkok ke kiri.','⬅️'],['right','Alih cahaya ke kanan','Pertumbuhan baharu membengkok ke kanan.','➡️']),'☀️'),
  q('Akar Mencari Air','plant-response','investigate','Uji kedudukan air dalam tanah model.','Letakkan air di dua lokasi berbeza dan jejak akar.','Akar menunjukkan gerak balas dengan tumbuh ke arah sumber air.',seq(['water-left','Letak air di kiri','Akar baharu menuju ke kiri.','💧'],['reset','Tetapkan semula model','Kedudukan awal dipulihkan.','↻'],['water-right','Letak air di kanan','Akar baharu menuju ke kanan.','💧']),'🌱'),
  q('Kilang Makanan Tumbuhan','photosynthesis','checklist','Sediakan keperluan asas fotosintesis.','Berikan cahaya, air, karbon dioksida dan daun berklorofil.','Tumbuhan hijau menggunakan cahaya, air dan karbon dioksida untuk membuat makanan serta membebaskan oksigen.',seq(['light','Sediakan cahaya','Cahaya membekalkan tenaga.','☀️'],['water','Sediakan air','Akar menyerap air.','💧'],['co2','Sediakan karbon dioksida','Karbon dioksida masuk melalui daun.','CO₂'],['chlorophyll','Gunakan daun hijau','Klorofil menyerap cahaya.','🍃']),'🍃'),
  q('Cabaran Fotosintesis','photosynthesis','investigate','Diagnos tumbuhan yang tidak dapat membuat makanan dengan baik.','Uji setiap keadaan dan baiki faktor yang hilang.','Fotosintesis memerlukan cahaya, air, karbon dioksida dan klorofil; makanan dihasilkan dan oksigen dibebaskan.',seq(['inspect','Periksa model','Model kekurangan cahaya dan air.','🔎'],['add-light','Tambahkan cahaya','Satu keperluan dipulihkan.','☀️'],['add-water','Tambahkan air','Keperluan asas lengkap.','💧'],['observe','Perhatikan hasil','Makanan dibuat dan oksigen ditunjukkan sebagai hasil.','O₂']),'🧪')
 ]);
 u('light-properties','Sifat Cahaya','🔦','Uji gerakan, pantulan dan pembiasan cahaya.',[
  q('Cahaya Bergerak Lurus','light4','sequence','Jajarkan tiga bukaan untuk laluan cahaya.','Alih kad sehingga semua lubang berada pada satu garis.','Cahaya bergerak dalam garis lurus melalui bukaan yang sejajar.',seq(['card1','Jajarkan kad 1','Bukaan pertama sejajar.','①'],['card2','Jajarkan kad 2','Bukaan kedua sejajar.','②'],['card3','Jajarkan kad 3','Sinar sampai ke skrin.','③']),'🔦'),
  q('Misteri Bayang-Bayang','light4','compare','Ubah jarak objek dan bandingkan bayang-bayang.','Gerakkan objek dekat dan jauh daripada lampu.','Objek lebih dekat dengan sumber cahaya menghasilkan bayang-bayang lebih besar pada skrin tetap.',seq(['near','Letak objek dekat lampu','Bayang-bayang menjadi besar.','🔍'],['far','Letak objek jauh dari lampu','Bayang-bayang menjadi lebih kecil.','▫️'],['shape','Pusing bentuk objek','Bentuk bayang-bayang boleh berubah.','🔄']),'🌑'),
  q('Cermin Memantul','light4','investigate','Halakan cahaya menggunakan cermin.','Putar cermin sehingga sinar mengenai sasaran.','Cermin memantulkan cahaya; arah pantulan berubah apabila orientasi cermin berubah.',seq(['shine','Nyalakan sinar','Sinar mengenai cermin.','🔦'],['turn','Putar cermin','Arah pantulan berubah.','🪞'],['target','Halakan ke sasaran','Sinar pantulan mengenai sasaran.','🎯']),'🪞'),
  q('Cahaya Membelok','light4','compare','Bandingkan pensel dalam udara dan air.','Masukkan pensel maya ke dalam air dan lihat dari sisi.','Pembiasan berlaku apabila cahaya berubah arah ketika bergerak antara dua medium; pensel kelihatan bengkok.',seq(['air','Periksa dalam udara','Pensel kelihatan lurus.','✏️'],['water','Masukkan ke dalam air','Pensel kelihatan bengkok pada permukaan air.','💧'],['side','Lihat dari sisi','Perubahan arah cahaya ditunjukkan.','👁️']),'🌈'),
  q('Makmal Cahaya','light4','sequence','Gabungkan tiga sifat cahaya dalam satu laluan.','Jajarkan bukaan, pantulkan sinar dan lalukan melalui air.','Cahaya bergerak lurus, boleh dipantulkan dan boleh dibiaskan.',seq(['align','Jajarkan bukaan','Sinar lurus melepasi kad.','🔦'],['reflect','Putar cermin','Sinar dipantulkan ke bekas.','🪞'],['refract','Lalukan melalui air','Sinar berubah arah.','💧'],['finish','Terangi sasaran','Ketiga-tiga sifat digunakan.','🎯']),'🔬')
 ]);
 u('sound','Bunyi','🎵','Lihat getaran, arah bunyi, gema dan kawalan hingar.',[
  q('Bunyi Daripada Getaran','sound4','compare','Hasilkan dan hentikan getaran tali maya.','Petik tali, perhatikan gelombang, kemudian sentuh untuk menghentikannya.','Bunyi dihasilkan oleh objek yang bergetar; apabila getaran berhenti bunyi juga berhenti.',seq(['pluck','Petik tali','Tali dan penunjuk gelombang bergetar.','〰️'],['touch','Sentuh tali','Getaran berhenti.','✋']),'🎸'),
  q('Bunyi Ke Semua Arah','sound4','checklist','Periksa pengesan di sekeliling sumber bunyi.','Aktifkan sumber kemudian periksa empat arah.','Bunyi bergerak ke semua arah daripada sumbernya.',seq(['source','Aktifkan loceng maya','Gelombang visual bermula.','🔔'],['north','Periksa arah utara','Pengesan menunjukkan bunyi.','⬆️'],['east','Periksa arah timur','Pengesan menunjukkan bunyi.','➡️'],['south','Periksa arah selatan','Pengesan menunjukkan bunyi.','⬇️'],['west','Periksa arah barat','Pengesan menunjukkan bunyi.','⬅️']),'🔊'),
  q('Gema!','sound4','compare','Bandingkan ruang terbuka dan dinding jauh.','Hantar denyut bunyi visual dalam dua tempat.','Gema terhasil apabila bunyi dipantulkan dan didengar semula selepas sela masa.',seq(['open','Uji ruang terbuka','Pantulan lemah dan tidak jelas.','🏞️'],['wall','Uji menghadap dinding jauh','Gelombang kembali sebagai gema.','🧱']),'📣'),
  q('Bunyi Baik atau Mengganggu?','sound4','classify','Kelaskan bunyi mengikut situasi dan kesannya.','Periksa tujuan dan aras setiap sumber; audio tidak diperlukan.','Bunyi boleh berfaedah atau memudaratkan bergantung pada aras, tempoh dan keadaan.',cls(['alarm','Penggera kecemasan','useful','Memberi amaran bahaya.','🚨'],['music','Muzik terlalu kuat lama','harmful','Boleh mengganggu dan menjejaskan pendengaran.','🔊'],['horn','Hon amaran ringkas','useful','Memberi amaran keselamatan.','📯'],['drill','Gerudi kuat tanpa perlindungan','harmful','Hingar kuat berpanjangan memudaratkan.','🛠️']),'👂'),
  q('Cabaran Kurangkan Bunyi','sound4','design','Pilih tindakan yang mengurangkan pencemaran bunyi.','Baiki bilik muzik dengan bahan dan tingkah laku sesuai.','Bahan lembut, penghadang, aras bunyi sederhana dan perlindungan telinga membantu mengurangkan kesan hingar.',cls(['curtain','Pasang langsir tebal','yes','Bahan lembut menyerap sebahagian bunyi.','🪟'],['volume','Rendahkan kelantangan','yes','Kurangkan bunyi pada sumber.','🔉'],['door','Tutup pintu','yes','Penghadang mengurangkan bunyi keluar.','🚪'],['amplify','Tambah pembesar suara','no','Ini menambah aras bunyi.','📢']),'🎧')
 ]);
 u('energy','Tenaga','⚡','Jejak sumber, bentuk dan perubahan tenaga.',[
  q('Dari Mana Tenaga Datang?','energy4','classify','Padankan sumber tenaga dengan contoh penggunaan.','Periksa sumber sebelum memadankan.','Matahari, makanan, bahan api, angin, air dan bateri ialah contoh sumber tenaga.',cls(['sun','Matahari','natural','Sumber cahaya dan haba utama Bumi.','☀️'],['food','Makanan','stored','Tenaga kimia untuk badan.','🍚'],['battery','Bateri','stored','Menyimpan tenaga kimia.','🔋'],['wind','Angin','natural','Udara bergerak boleh menggerakkan turbin.','🌬️']),'⚡'),
  q('Kenali Bentuk Tenaga','energy4','classify','Kelaskan tenaga melalui kesan yang diperhatikan.','Periksa lampu, seterika, kipas dan radio.','Tenaga dapat hadir sebagai cahaya, haba, elektrik, bunyi, kinetik, kimia atau keupayaan.',cls(['lamp','Lampu menyala','light','Kesan utama yang diperhatikan ialah cahaya.','💡'],['iron','Seterika panas','heat','Kesan utama ialah haba.','♨️'],['fan','Kipas bergerak','kinetic','Bilah bergerak mempunyai tenaga kinetik.','🌀'],['radio','Radio berbunyi','sound','Pembesar suara menghasilkan bunyi.','📻']),'🔋'),
  q('Tenaga Berubah Bentuk','energy4','sequence','Jejak perubahan tenaga dalam lampu suluh.','Aktifkan bateri, arus dan mentol mengikut urutan.','Dalam lampu suluh, tenaga kimia bateri berubah kepada tenaga elektrik, kemudian cahaya dan haba.',seq(['chemical','Tenaga kimia bateri','Tenaga tersimpan tersedia.','🔋'],['electrical','Aliran tenaga elektrik','Litar memindahkan tenaga.','⚡'],['light','Cahaya dan sedikit haba','Mentol menghasilkan dua bentuk tenaga.','💡']),'🔦'),
  q('Boleh Diperbaharui atau Tidak?','energy4','classify','Kelaskan sumber berdasarkan kebolehbaharuan.','Periksa sama ada sumber boleh diganti secara semula jadi dalam masa sesuai.','Matahari, angin dan air boleh dibaharui; arang batu dan petroleum tidak boleh dibaharui pada kadar penggunaan manusia.',cls(['sun','Matahari','renewable','Terus membekalkan tenaga.','☀️'],['wind','Angin','renewable','Aliran udara tersedia semula.','🌬️'],['water','Air mengalir','renewable','Kitaran air memperbaharuinya.','💧'],['coal','Arang batu','nonrenewable','Mengambil masa amat lama untuk terbentuk.','⬛'],['oil','Petroleum','nonrenewable','Bekalan terhad.','🛢️']),'🌍'),
  q('Jejak Tenaga','energy4','sequence','Lengkapkan rantaian tenaga panel suria dan kipas.','Jejak tenaga daripada Matahari hingga gerakan kipas.','Tenaga cahaya Matahari berubah kepada tenaga elektrik dan kemudian tenaga kinetik serta bunyi pada kipas.',seq(['sun','Cahaya Matahari','Sumber tenaga masuk.','☀️'],['panel','Panel suria menghasilkan elektrik','Tenaga berubah bentuk.','🔷'],['motor','Motor menerima elektrik','Motor mula bergerak.','⚙️'],['fan','Kipas bergerak dan berbunyi','Tenaga kinetik dan bunyi terhasil.','🌀']),'♻️')
 ]);
 u('materials','Bahan','🧱','Uji sumber dan sifat bahan untuk mereka cipta.',[
  q('Dari Mana Bahan Datang?','materials4','classify','Kelaskan objek mengikut sumber asas bahan.','Periksa kayu, kapas, kulit dan plastik.','Bahan boleh berasal daripada tumbuhan, haiwan, batuan atau petroleum.',cls(['paper','Kertas','plant','Dibuat daripada pulpa kayu.','📄'],['shirt','Baju kapas','plant','Kapas ialah gentian tumbuhan.','👕'],['leather','Tali kulit','animal','Kulit berasal daripada haiwan.','👜'],['metal','Sudu logam','rock','Logam diperoleh daripada bijih dalam batuan.','🥄'],['plastic','Bekas plastik','petroleum','Kebanyakan plastik dibuat daripada petroleum.','🧴']),'🏭'),
  q('Kenali Sifat Bahan','materials4','compare','Uji beberapa sifat bahan secara maya.','Lentur, titis air dan suluh bahan.','Bahan mempunyai sifat berbeza seperti fleksibel, kuat, telus, menyerap air atau kalis air.',seq(['bend','Lentur getah','Getah fleksibel.','🟠'],['drop','Titis air pada kain','Kain menyerap air.','💧'],['shine','Suluh kaca','Kaca lutsinar membenarkan cahaya melaluinya.','🔦'],['pull','Tarik tali nilon','Tali nilon model ini kuat.','🪢']),'🧪'),
  q('Pilih Bahan Sesuai','materials4','design','Pilih bahan berdasarkan tujuan objek.','Padankan payung, tingkap dan tuala dengan sifat penting.','Pemilihan bahan bergantung pada sifat yang diperlukan oleh objek.',cls(['umbrella','Payung: plastik berlapis','yes','Kalis air dan ringan.','☂️'],['window','Tingkap: kaca','yes','Lutsinar dan keras.','🪟'],['towel','Tuala: kapas','yes','Menyerap air.','🧻'],['paper-window','Tingkap: kertas','no','Tidak lutsinar dan mudah rosak oleh air.','📄']),'🛠️'),
  q('Serap atau Kalis Air?','materials4','compare','Uji empat bahan dengan jumlah air sama.','Titis air dan catat sama ada diserap atau kekal di permukaan.','Kain dan kertas menyerap air; plastik dan getah kalis air dalam model ini.',seq(['cloth','Uji kain','Air diserap.','🧵'],['paper','Uji kertas','Air diserap dan kertas melemah.','📄'],['plastic','Uji plastik','Air kekal di permukaan.','🧴'],['rubber','Uji getah','Air tidak diserap.','🟠']),'💧'),
  q('Jurutera Bahan','materials4','sequence','Reka bekas minuman berdasarkan sifat bahan.','Pilih lapisan, badan dan pemegang yang sesuai.','Objek boleh menggabungkan beberapa bahan supaya setiap bahagian menjalankan fungsi yang sesuai.',seq(['body','Pilih badan kuat dan kalis air','Bekas tidak mudah bocor.','🥤'],['handle','Pilih pemegang penebat haba','Tangan dilindungi daripada haba.','🖐️'],['lid','Pilih penutup fleksibel rapat','Cecair sukar tertumpah.','🔒'],['test','Uji reka bentuk','Semua keperluan fungsi dipenuhi.','✅']),'👷')
 ]);
 u('earth','Bumi','🌍','Siasat graviti, putaran dan peredaran Bumi.',[
  q('Tarikan Bumi','earth4','compare','Uji objek di beberapa lokasi pada glob model.','Lepaskan objek dari atas, sisi dan bawah glob.','Graviti menarik objek ke arah pusat Bumi; “bawah” setempat ialah menuju ke permukaan Bumi.',seq(['top','Lepas objek di atas glob','Objek bergerak menuju permukaan.','⬇️'],['side','Lepas objek di sisi glob','Arah tarikan menuju pusat glob.','➡️'],['bottom','Lepas objek di bawah glob','Arah tarikan tetap menuju pusat glob.','⬆️']),'🌍'),
  q('Jatuh Ke Mana?','earth4','investigate','Ramalkan dan uji arah jatuh beberapa objek.','Lepaskan bola dan daun maya tanpa angin.','Semua objek ditarik ke arah Bumi; rintangan udara boleh mempengaruhi cara objek jatuh tetapi bukan arah graviti.',seq(['ball','Lepaskan bola','Bola jatuh ke permukaan.','⚽'],['leaf','Lepaskan daun tanpa angin','Daun juga bergerak ke permukaan.','🍂'],['globe','Periksa glob','Objek di seluruh Bumi kekal pada permukaan kerana graviti.','🌍']),'⬇️'),
  q('Putaran Bumi','earth4','sequence','Putarkan Bumi pada arah dan tempoh model yang betul.','Tetapkan arah barat ke timur dan majukan 24 jam maya.','Bumi berputar pada paksinya dari barat ke timur dalam kira-kira 24 jam.',seq(['axis','Tunjukkan paksi Bumi','Paksi ialah garis bayangan tempat Bumi berputar.','↕️'],['direction','Pilih barat ke timur','Arah putaran ditetapkan.','↪️'],['rotate','Majukan 24 jam maya','Satu putaran lengkap.','🕛']),'🌍'),
  q('Siang dan Malam','earth4','compare','Perhatikan lokasi ketika Bumi berputar.','Putar lokasi ke arah dan menjauhi Matahari.','Bahagian Bumi yang menghadap Matahari mengalami siang; bahagian yang membelakanginya mengalami malam.',seq(['face','Hadapkan lokasi kepada Matahari','Lokasi menerima cahaya: siang.','☀️'],['turn','Putar Bumi separuh pusingan','Lokasi bergerak ke sisi gelap.','🔄'],['away','Perhatikan lokasi membelakangi Matahari','Lokasi mengalami malam.','🌙']),'🌗'),
  q('Cabaran Bumi Bergerak','earth4','sequence','Bezakan putaran dan peredaran serta kesannya.','Lengkapkan model harian dan tahunan.','Bumi berputar pada paksinya kira-kira 24 jam dan beredar mengelilingi Matahari kira-kira 365¼ hari; putaran menyebabkan siang dan malam.',seq(['spin','Lengkapkan satu putaran','24 jam maya berlalu.','🌍'],['daynight','Catat siang dan malam','Kesan putaran dikenal pasti.','🌗'],['orbit','Lengkapkan satu peredaran','Kira-kira 365¼ hari maya berlalu.','☀️'],['compare','Bandingkan dua gerakan','Putaran dan peredaran tidak sama.','📊']),'🌎')
 ]);
 u('machines','Mesin','⚙️','Gunakan tuas dan gabungan mesin ringkas untuk menyelesaikan masalah.',[
  q('Kenali Mesin Ringkas','machines4','classify','Kelaskan mesin ringkas dalam objek harian.','Periksa fungsi setiap objek.','Mesin ringkas termasuk tuas, gear, takal, baji, skru, satah condong serta roda dan gandar.',cls(['ramp','Tanjakan','inclined','Permukaan condong membantu memindahkan beban.','📐'],['knife','Pisau','wedge','Baji memisahkan bahan.','🔪'],['doorknob','Tombol pintu','wheel','Roda dan gandar membantu memutar.','🚪'],['jar','Penutup balang berulir','screw','Skru ialah satah condong berlingkar.','🫙'],['bike','Gear basikal','gear','Gigi gear memindahkan gerakan.','🚲']),'⚙️'),
  q('Pilih Alat Yang Sesuai','machines4','design','Pilih mesin ringkas untuk tiga masalah.','Pilih alat berdasarkan kerja yang perlu dilakukan.','Mesin ringkas dipilih mengikut cara ia membantu menyelesaikan masalah.',cls(['ramp','Naikkan kotak ke lori: tanjakan','yes','Satah condong menyediakan laluan.','📦'],['crowbar','Angkat penutup: tuil','yes','Tuil berputar pada fulkrum.','🛠️'],['pulley','Naikkan bendera: takal','yes','Takal mengubah arah tarikan.','🚩'],['spoon','Naikkan kotak: sudu','no','Sudu tidak sesuai untuk beban besar.','🥄']),'🧰'),
  q('Tuas Membantu','lever4','investigate','Ubah kedudukan fulkrum dan bandingkan daya model.','Letakkan beban, fulkrum dan daya lalu uji dua jarak.','Apabila fulkrum lebih dekat kepada beban, daya yang diperlukan pada hujung yang jauh menjadi lebih kecil dalam model tuas.',seq(['load','Letakkan beban','Beban dikenal pasti.','📦'],['fulcrum-far','Uji fulkrum jauh daripada beban','Model menunjukkan daya lebih besar.','🔺'],['fulcrum-near','Alih fulkrum dekat beban','Lengan daya menjadi lebih panjang.','🔺'],['compare','Bandingkan daya','Daya model lebih kecil apabila fulkrum dekat beban.','📊']),'⚖️'),
  q('Mesin Dalam Kehidupan','machines4','classify','Cari gabungan mesin ringkas dalam mesin kompleks.','Periksa basikal, gunting dan kereta sorong.','Mesin kompleks menggabungkan dua atau lebih mesin ringkas.',cls(['bicycle','Basikal','complex','Menggabungkan roda dan gandar, gear, tuas dan skru.','🚲'],['scissors','Gunting','complex','Menggabungkan tuas dan baji.','✂️'],['wheelbarrow','Kereta sorong','complex','Menggabungkan tuas serta roda dan gandar.','🛒'],['ramp','Tanjakan sahaja','simple','Satu satah condong ialah mesin ringkas.','📐']),'🏗️'),
  q('Cabaran Cipta Mesin','machines4','sequence','Reka alat untuk memindahkan kotak berat.','Gabungkan mesin ringkas, uji dan baiki reka bentuk.','Gabungan satah condong, roda dan gandar serta tuas boleh membentuk mesin kompleks untuk menyelesaikan masalah.',seq(['ramp','Tambah satah condong','Kotak boleh digerakkan beransur-ansur.','📐'],['wheels','Tambah roda dan gandar','Geseran gerakan dikurangkan.','🛞'],['lever','Tambah tuas pemegang','Arah dan kawalan daya bertambah baik.','🛠️'],['test','Uji mesin kompleks','Kotak berjaya dipindahkan.','✅']),'👷')
 ]);
})();
