'use strict';
window.MakmalJournal=(()=>{
 const p=()=>window.MakmalProgress,esc=v=>window.MakmalProfiles.esc(v),totals={1:50,2:35,3:50,4:50,5:50,6:55};
 const registries=()=>({1:window.MakmalYear1,3:window.MakmalYear3,4:window.MakmalYear4,5:window.MakmalYear5,6:window.MakmalYear6});
 function yearUnits(year){if(year===2)return window.MakmalContent.year2Units;return registries()[year]?.units||[];}
 function definition(year,id){if(year!==2)return registries()[year]?.missions[id]||null;return window.MakmalNewContent?.missions[id]||window.MakmalPlantContent?.missions[id]||window.MakmalMixtureContent?.missions[id]||window.MakmalLightContent?.missions[id]||window.MakmalCircuitMissions?.[id]||(id==='electricity-2'?window.MakmalMission2:id==='electricity-1'?window.MakmalMission1:null);}
 function getMission(year,unitId,missionId){year=Number(year);const unit=yearUnits(year).find(u=>u.id===unitId),summary=unit?.missions.find(m=>m.id===missionId);if(!unit||!summary)return null;const def=definition(year,missionId)||{},number=summary.number||def.number,progressKey=def.progressKey||`mission${number}`,storageUnit=year===2?p().storageUnit(unit.id):unit.id,record=p().getData().progress[`year${year}`]?.[storageUnit]?.[progressKey]||{},presentation=window.MakmalExperienceContent?.[missionId]||{};return {year,unit,summary,def,number,progressKey,storageUnit,record,title:def.title||summary.title,discovery:def.discovery||presentation.discovery||'',completed:record.completed===true};}
 function all(){const result=[];for(let year=1;year<=6;year++)for(const unit of yearUnits(year))for(const mission of unit.missions){const item=getMission(year,unit.id,mission.id);if(item)result.push(item);}return result;}
 const yearProgress=year=>p().allYearsSummary().find(x=>x.year===Number(year));
 const bar=(value,total,label)=>`<div class="journal-progress" role="progressbar" aria-label="${esc(label)}: ${value} daripada ${total}" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${value}"><span style="--progress:${Math.round(value/total*100)}%"></span></div>`;
 const fmt=date=>{if(!date)return '';try{return new Intl.DateTimeFormat('ms-MY',{dateStyle:'medium'}).format(new Date(date));}catch(_){return '';}};
 const complete=item=>item.completed,available=item=>item.year===2?p().isAvailable(item.number,item.storageUnit):p().forYear(item.year).isAvailable(item.number,item.storageUnit);
 function recent(){return all().filter(x=>x.completed&&typeof x.record.completedAt==='string').sort((a,b)=>b.record.completedAt.localeCompare(a.record.completedAt)).slice(0,5);}
 function continueMission(){const entries=all(),latest=recent()[0];if(latest){const same=entries.find(x=>x.year===latest.year&&x.storageUnit===latest.storageUnit&&!x.completed&&available(x));if(same)return same;}return entries.find(x=>!x.completed&&available(x))||null;}
 function playRoute(item){return item.year===2?{screen:'experiment',context:{unitId:item.unit.id,missionId:item.summary.id}}:{screen:`year${item.year}Experiment`,context:{unitId:item.unit.id,missionId:item.summary.id}};}
 function home(){const profile=p().getActiveProfile(),stats=p().profileStats(),latest=recent(),next=continueMission(),empty=stats.completed===0,full=stats.completed===290;return `<section class="journal"><header class="journal-hero">${window.MakmalProfiles.avatar(profile.avatar,profile.name)}<div><p class="section-kicker">REKOD PEMBELAJARAN TEMPATAN</p><h1>Buku Makmal ${esc(profile.name)}</h1><p><strong>${stats.completed} / 290</strong> eksperimen ditemui · ${stats.units} / 58 unit</p>${bar(stats.completed,290,'Kemajuan keseluruhan')}</div></header>${empty?`<section class="journal-empty"><h2>Buku Makmal kamu masih kosong.</h2>${window.MakmalPico.dialogue('Penemuan pertama menanti!','curious')}<p>Jom buat eksperimen pertama!</p><button class="primary" data-journal-play="first">Mula Bereksperimen</button></section>`:''}${full?'<section class="journal-complete"><h2>BUKU MAKMAL LENGKAP!</h2><p>Kamu telah menemui semua eksperimen Sains Tahun 1 hingga Tahun 6.</p><strong>6 / 6 tahun · 58 / 58 unit · 290 / 290 eksperimen</strong></section>':''}<div class="journal-years">${p().allYearsSummary().map(y=>`<button class="journal-year-card" data-journal-year="${y.year}"><span><small>TAHUN</small><strong>${y.year}</strong></span><span>${y.completed} / ${y.total} eksperimen ${y.completed===y.total?'· ✓ Selesai':''}</span>${bar(y.completed,y.total,`Tahun ${y.year}`)}</button>`).join('')}</div>${!empty?`<section class="journal-recent"><h2>PENEMUAN TERKINI</h2>${latest.length?`<div>${latest.map(x=>`<button data-journal-mission="${x.summary.id}" data-journal-unit="${x.unit.id}" data-journal-mission-year="${x.year}"><strong>${esc(x.title)}</strong><span>${esc(x.unit.title)} · Tahun ${x.year}</span><small>${fmt(x.record.completedAt)}</small></button>`).join('')}</div>`:'<p>Tiada tarikh penemuan tersedia.</p>'}</section>`:''}${!empty&&next?`<button class="primary journal-continue" data-journal-play="${next.summary.id}" data-journal-unit="${next.unit.id}" data-journal-play-year="${next.year}">SAMBUNG EKSPERIMEN →</button>`:''}</section>`;}
 function year(year){const stats=yearProgress(year),units=yearUnits(Number(year));return `<section class="journal"><div class="screen-heading"><p class="section-kicker">BUKU MAKMAL</p><h1>BUKU MAKMAL — TAHUN ${year}</h1><p>${stats.completed} / ${stats.total} eksperimen ditemui</p>${bar(stats.completed,stats.total,`Kemajuan Tahun ${year}`)}</div><div class="journal-unit-grid">${units.map(unit=>{const entries=unit.missions.map(m=>getMission(Number(year),unit.id,m.id)),count=entries.filter(complete).length;return `<button class="journal-unit-card" data-journal-unit="${unit.id}" data-journal-year="${year}"><span aria-hidden="true">${unit.emoji||'🔬'}</span><strong>${esc(unit.title)}</strong><span>${count} / 5 eksperimen</span>${bar(count,5,unit.title)}<small>${count===5?'✓ Selesai':'Belum selesai'}</small></button>`;}).join('')}</div></section>`;}
 function unit(year,unitId){const details=yearUnits(Number(year)).find(u=>u.id===unitId);if(!details)return '';const entries=details.missions.map(m=>getMission(Number(year),unitId,m.id));return `<section class="journal"><div class="screen-heading"><p class="section-kicker">BUKU MAKMAL · TAHUN ${year}</p><h1>${esc(details.title)}</h1><p>${entries.filter(complete).length} / 5 eksperimen ditemui</p>${bar(entries.filter(complete).length,5,details.title)}</div><div class="journal-missions">${entries.map(x=>{const fresh=x.completed&&!p().isDiscoveryViewed(x.year,x.storageUnit,x.progressKey);return `<button data-journal-mission="${x.summary.id}" data-journal-unit="${x.unit.id}" data-journal-mission-year="${x.year}"><span class="journal-mission-number">${x.number}</span><span><strong>${x.completed?'✓ ':''}${esc(x.title)}</strong><small>${x.completed?`Selesai${fmt(x.record.completedAt)?' · '+fmt(x.record.completedAt):''}`:'Belum ditemui'}</small></span>${fresh?'<span class="badge">BARU</span>':''}</button>`;}).join('')}</div></section>`;}
 function mission(year,unitId,missionId){const item=getMission(Number(year),unitId,missionId);if(!item)return '';const fresh=item.completed&&!p().isDiscoveryViewed(item.year,item.storageUnit,item.progressKey),canPlay=available(item),route=playRoute(item);if(item.completed)p().markDiscoveryViewed(item.year,item.storageUnit,item.progressKey);if(fresh)window.MakmalFeedback?.emit('discovery');return `<section class="journal journal-entry"><p class="section-kicker">BUKU MAKMAL · TAHUN ${item.year} · ${esc(item.unit.title)}</p><h1>${item.completed?'✓ ':''}${esc(item.title)}</h1>${item.completed?`<div class="journal-discovery"><span>TEMUI</span><blockquote>${esc(item.discovery)}</blockquote><p><strong>Selesai:</strong> ${fmt(item.record.completedAt)||'Tarikh tidak tersedia'}</p></div>`:`<div class="journal-locked"><h2>Belum ditemui</h2><p>${canPlay?'Eksperimen ini sedia untuk diterokai.':'Lengkapkan misi sebelumnya dahulu.'}</p></div>`}${canPlay?`<button class="primary" data-journal-direct-screen="${route.screen}" data-journal-direct-unit="${item.unit.id}" data-journal-direct-mission="${item.summary.id}">${item.completed?'Main Semula':'Main Misi'} →</button>`:''}</section>`;}
 function audit(){const entries=all();return {entries,total:entries.length,missing:entries.filter(x=>!x.title||!x.unit||!x.year||!x.discovery.trim()),generic:entries.filter(x=>/^(tahniah|betul|hebat)[!. ]*$/i.test(x.discovery.trim()))};}
 return {totals,yearUnits,getMission,all,recent,continueMission,playRoute,home,year,unit,mission,audit};
})();
