'use strict';
window.MakmalProfiles=(()=>{
  const p=()=>window.MakmalProgress;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const marks={pico:'🤖',flask:'⚗️',microscope:'🔬',planet:'🪐',bulb:'💡',leaf:'🌱'};
  const avatar=(id,label='')=>`<span class="profile-avatar avatar-${esc(id)}" role="img" aria-label="Avatar ${esc(label||id)}">${marks[id]||marks.pico}</span>`;
  const choices=selected=>`<fieldset class="avatar-choices"><legend>Pilih avatar</legend>${p().AVATARS.map(id=>`<label><input type="radio" name="avatar" value="${id}" ${id===selected?'checked':''}>${avatar(id,id)}<span>${({pico:'PICO',flask:'Kelalang',microscope:'Mikroskop',planet:'Planet',bulb:'Mentol',leaf:'Daun'})[id]}</span></label>`).join('')}</fieldset>`;
  function select(){const profiles=p().getProfiles(),active=p().getData().activeProfileId;return `<section class="profile-shell"><div class="screen-heading"><p class="section-kicker">PROFIL TEMPATAN</p><h1>PILIH PEMAIN</h1><p>Setiap pemain mempunyai kemajuan sendiri pada peranti ini.</p></div><div class="profile-grid">${profiles.map(x=>{const s=p().profileStats(x.id),selected=x.id===active;return `<div class="profile-card-wrap"><button class="profile-card ${selected?'selected':''}" data-select-profile="${esc(x.id)}"${selected?' aria-current="true"':''}>${avatar(x.avatar,x.name)}<strong>${esc(x.name)}</strong>${selected?'<span class="current-profile">✓ Pemain aktif</span>':''}<span>${s.completed} / 290 eksperimen</span><span class="profile-meter"><i style="width:${s.percentage}%"></i></span></button><button class="profile-manage" data-edit-profile="${esc(x.id)}" aria-label="Urus profil ${esc(x.name)}">Urus</button></div>`;}).join('')}${profiles.length<p().MAX_PROFILES?'<button class="profile-card add-profile" data-route="profileCreate"><span class="profile-plus">＋</span><strong>Tambah Pemain</strong><span>Maksimum 6 profil</span></button>':''}</div><p class="privacy-note">Profil dan kemajuan disimpan secara tempatan pada peranti ini.</p></section>`;}
  function form(mode,context={}){const editing=mode!=='create',profile=editing?p().getProfiles().find(x=>x.id===context.profileId)||p().getActiveProfile():null;return `<section class="profile-form-card"><p class="section-kicker">${editing?'URUS PROFIL':'PEMAIN BAHARU'}</p><h1>${editing?'Edit Profil':'Tambah Pemain'}</h1><form data-profile-form="${mode}" data-profile-id="${profile?.id||''}"><label class="field-label" for="profile-name">Nama ringkas</label><input id="profile-name" name="name" maxlength="20" autocomplete="off" required value="${esc(profile?.name||'')}" placeholder="Contoh: Sofia">${choices(profile?.avatar||'pico')}<p class="form-error" role="alert" hidden></p><div class="form-actions"><button class="primary" type="submit">${editing?'Simpan Perubahan':'Tambah Pemain'}</button><button class="nav-button" type="button" data-action="back">Batal</button></div></form>${mode==='parentEdit'?`<button class="danger-button" data-delete-profile="${esc(profile.id)}">Padam Profil</button>`:''}</section>`;}
  const fmt=date=>{if(!date)return 'Belum ada';try{return new Intl.DateTimeFormat('ms-MY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(date));}catch(_){return 'Belum ada';}};
  function dashboard(context={}){const profiles=p().getProfiles(),id=profiles.some(x=>x.id===context.profileId)?context.profileId:p().getData().activeProfileId,s=p().profileStats(id);return `<section class="parent-zone"><div class="parent-heading"><p class="section-kicker">UNTUK ORANG DEWASA</p><h1>RUANG IBU BAPA / PENJAGA</h1><p>Kemajuan sebenar yang disimpan pada peranti ini.</p></div><label class="field-label" for="parent-profile">Pilih pemain</label><select id="parent-profile" data-parent-profile>${profiles.map(x=>`<option value="${esc(x.id)}" ${x.id===id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><section class="parent-summary">${avatar(s.profile.avatar,s.profile.name)}<div><h2>${esc(s.profile.name)}</h2><strong>${s.completed} / 290 eksperimen</strong><span>${s.percentage}% selesai · ${s.units} / 58 unit</span></div></section><div class="year-progress-table" role="table" aria-label="Kemajuan mengikut tahun">${s.years.map(y=>`<div role="row"><strong role="cell">Tahun ${y.year}</strong><span role="cell">${y.completed} / ${y.total} eksperimen</span><span role="cell">${y.units} unit selesai · ${y.unitTotal-y.units} belum selesai</span></div>`).join('')}</div><div class="parent-facts"><p><strong>Jumlah percubaan:</strong> ${s.attempts}</p><p><strong>Aktiviti terkini:</strong> ${fmt(s.latest||s.profile.lastPlayedAt)}</p></div><div class="parent-actions"><button class="nav-button" data-parent-edit-profile="${esc(id)}">Edit Profil</button><button class="nav-button" data-route="parentProfileCreate">Tambah Pemain</button><button class="danger-button" data-reset-profile="${esc(id)}">Reset Kemajuan</button><button class="support-button" data-route="support">Sokong Pembangunan</button></div><section class="parent-info"><h2>Tentang Makmal Cilik</h2><p>Game pendidikan Sains Tahun 1 hingga Tahun 6 dengan 58 unit dan 290 eksperimen. Pembelajaran mengikuti Ramal → Cuba → Perhati → Fikir → Temui.</p><p>Tiada akaun diperlukan. Kemajuan disimpan pada peranti, tanpa analytics, tracker atau iklan bertarget. Semua kandungan pembelajaran tersedia tanpa bayaran.</p></section></section>`;}
  function gate(){return `<section class="adult-gate"><span class="gate-lock" aria-hidden="true">🔒</span><p class="section-kicker">UNTUK IBU BAPA / PENJAGA</p><h1>Pengesahan Orang Dewasa</h1><p>Tahan butang selama kira-kira 3 saat. Ini mengurangkan kemasukan tidak sengaja oleh kanak-kanak.</p><button class="hold-button" data-adult-gate aria-describedby="gate-help"><span>Tahan untuk masuk</span><i aria-hidden="true"></i></button><p id="gate-help">Tetikus atau sentuhan: tekan dan tahan. Papan kekunci: tahan Space atau Enter.</p><button class="nav-button" data-route="parentGateConfirm">Alternatif akses papan kekunci</button></section>`;}
  function support(){return `<section class="support-screen"><div class="support-copy"><p class="section-kicker">SOKONGAN SUKARELA</p><h1>SOKONG PEMBANGUNAN</h1><p>Sokongan anda membantu pembangunan dan penyelenggaraan Makmal Cilik, termasuk aset visual, audio, ujian peranti, hosting, tools serta kos penerbitan dan Play Store.</p><p class="support-policy"><strong>Makmal Cilik boleh dimainkan sepenuhnya tanpa bayaran.</strong> Sokongan adalah sukarela dan tidak membuka kandungan tambahan.</p><div class="support-amounts" aria-label="Cadangan jumlah sokongan"><span>RM4.90</span><span>RM9.90</span><span>RM19.90</span></div><p>Imbas QR menggunakan aplikasi perbankan atau eWallet yang serasi. Pembayaran berlaku di luar aplikasi dan tidak disahkan oleh Makmal Cilik.</p><p class="thanks">Terima kasih atas sokongan anda.</p></div><figure class="support-poster"><a href="assets/support/makmal-cilik-support.webp" target="_blank" rel="noopener" aria-label="Buka poster QR sokongan pada saiz penuh"><img src="assets/support/makmal-cilik-support.webp" alt="Poster Sokong Makmal Cilik dengan QR Touch 'n Go eWallet dan Malaysia National QR" width="1024" height="1536"></a><figcaption>Tekan poster untuk paparan QR yang lebih besar.</figcaption></figure></section>`;}
  return {select,form,dashboard,gate,support,avatar,esc};
})();
