'use strict';
(()=>{const Y=window.MakmalYear5;
 const u=(id,title,icon,description,missions)=>Y.addUnit({id,title,icon,description,totalMissions:5},missions);
 const q=(title,domain,mode,objective,instruction,discovery,actions,scene)=>({title,domain,mode,objective,instruction,discovery,scene,observations:[discovery,'Bukti pada model menyokong penemuan ini.'],question:'Apakah kesimpulan yang disokong oleh penyiasatan?',answers:[discovery,'Ramalan awal sentiasa mesti betul.'],actions});
 const seq=(...x)=>x.map(([id,label,note,art])=>({id,label,note,art}));
 const cls=(...x)=>x.map(([id,label,target,note,art])=>({id,label,target,note,art}));
 u('science-skills','Kemahiran Saintifik','📊','Tafsir data, kawal pemboleh ubah dan jalankan eksperimen.',[
  q('Cari Pola','data5','sequence','Kenal pasti pola daripada bacaan pertumbuhan.','Susun rekod hari 1 hingga hari 4 lalu bandingkan ukurannya.','Pola ialah perubahan teratur dalam data; tinggi anak pokok meningkat mengikut masa dalam rekod ini.',seq(['d1','Hari 1: 2 cm','Bacaan awal ialah 2 cm.','2'],['d2','Hari 2: 4 cm','Tinggi bertambah 2 cm.','4'],['d3','Hari 3: 6 cm','Pertambahan yang sama berterusan.','6'],['d4','Hari 4: 8 cm','Pola +2 cm dikenal pasti.','8']),'📈'),
  q('Tafsir Data','data5','classify','Tafsir jadual suhu air tanpa meneka.','Periksa setiap bacaan kemudian kelaskan sebagai meningkat, tetap atau menurun.','Tafsiran data menerangkan pola yang ditunjukkan oleh ukuran, bukan pendapat.',cls(['a','20°C → 30°C','increase','Suhu meningkat 10°C.','↗'],['b','30°C → 30°C','same','Suhu tidak berubah.','→'],['c','30°C → 24°C','decrease','Suhu menurun 6°C.','↘']),'📋'),
  q('Kawal Pemboleh Ubah','variables5','classify','Kenal pasti pemboleh ubah dalam ujian kadar pelarutan.','Padankan suhu air, masa larut dan jumlah gula dengan peranannya.','Ujian adil mengubah suhu air, mengukur masa melarut dan mengekalkan jumlah gula serta air.',cls(['temperature','Suhu air','manipulated','Suhu air sengaja diubah.','🌡️'],['time','Masa untuk larut','responding','Masa direkod sebagai hasil.','⏱️'],['sugar','Jumlah gula dan air','controlled','Jumlah bahan dikekalkan sama.','🥄']),'⚖️'),
  q('Bina Hipotesis','hypothesis5','select','Pilih hipotesis yang menghubungkan dua pemboleh ubah.','Periksa tiga pernyataan tentang suhu dan masa pelarutan.','Hipotesis boleh diuji: jika suhu air meningkat, masa gula melarut mungkin berkurang.',cls(['test','Jika suhu meningkat, masa melarut mungkin berkurang.','yes','Kedua-dua pemboleh ubah boleh diukur.','✅'],['opinion','Air panas paling bagus.','no','Ini pendapat dan tidak menetapkan ukuran.','💭'],['vague','Gula akan berubah.','no','Hubungan pemboleh ubah tidak jelas.','❓']),'🧪'),
  q('Penyiasatan Lengkap','inquiry5','sequence','Gabungkan hipotesis, kawalan, ukuran dan kesimpulan.','Jalankan ujian maya gula dalam dua suhu air.','Kesimpulan yang sah dibina daripada ujian adil, ukuran dan pola data walaupun ramalan awal berbeza.',seq(['hypothesis','Catat hipotesis','Hubungan suhu dengan masa dinyatakan.','💭'],['control','Samakan air dan gula','Pemboleh ubah lain dikawal.','⚖️'],['test','Uji dua suhu','Kedua-dua keadaan diuji.','🌡️'],['measure','Rekod masa','Masa menjadi definisi operasi kadar pelarutan.','⏱️'],['conclude','Tafsir keputusan','Kesimpulan merujuk data.','📝']),'🔬')
 ]);
 u('humans','Manusia','🫀','Terokai rangka, sendi dan peredaran darah asas.',[
  q('Kenali Sistem Rangka','body5','classify','Kenal pasti fungsi utama bahagian rangka.','Periksa tengkorak, tulang belakang dan anggota.','Rangka menyokong badan, melindungi organ dan membantu pergerakan bersama otot dan sendi.',cls(['skull','Tengkorak','protect','Melindungi otak.','💀'],['spine','Tulang belakang','support','Menyokong tubuh.','🦴'],['limb','Tulang anggota','move','Membantu pergerakan.','🦵']),'🩻'),
  q('Sendi dan Pergerakan','body5','classify','Padankan sendi dengan gerakan asas.','Uji model siku, bahu dan leher tanpa perlu bergerak sendiri.','Sendi menghubungkan tulang dan membenarkan jenis pergerakan yang berbeza.',cls(['elbow','Siku','hinge','Membengkok dan melurus seperti engsel.','💪'],['shoulder','Bahu','ball','Bergerak dalam banyak arah.','⭕'],['neck','Leher','pivot','Membolehkan kepala berpusing.','↔']),'🦴'),
  q('Laluan Darah','circulation5','sequence','Susun laluan peredaran darah pada model ringkas.','Jejak darah daripada jantung ke badan dan kembali.','Jantung mengepam darah melalui salur darah ke seluruh badan dan darah kembali ke jantung.',seq(['heart-out','Jantung mengepam keluar','Pam memulakan aliran.','🫀'],['artery','Melalui salur ke badan','Darah bergerak ke tisu badan.','🔴'],['body','Sampai ke seluruh badan','Bahan yang diperlukan dibawa.','🧍'],['vein','Kembali melalui salur','Darah bergerak kembali.','🔵'],['heart-in','Kembali ke jantung','Kitaran boleh berulang.','🫀']),'🩸'),
  q('Jantung Bekerja','circulation5','compare','Bandingkan kadar denyutan model ketika rehat dan aktif.','Uji dua keadaan dan kira denyutan visual selama sela masa sama.','Jantung berdenyut lebih cepat apabila badan aktif untuk mengedarkan darah mengikut keperluan badan.',seq(['rest','Periksa keadaan rehat','Denyutan model lebih perlahan.','💙'],['active','Periksa keadaan aktif','Denyutan model lebih cepat.','❤️'],['compare','Bandingkan dalam masa sama','Perbandingan dibuat secara adil.','⏱️']),'🫀'),
  q('Cabaran Sistem Tubuh','body5','sequence','Hubungkan rangka, otot, pernafasan dan peredaran secara asas.','Bantu model badan melakukan aktiviti dengan menyusun fungsi sistem.','Sistem badan bekerjasama: rangka dan otot membantu gerakan, pernafasan membekalkan oksigen dan peredaran membawa bahan ke seluruh badan.',seq(['support','Rangka menyokong','Tubuh mempunyai bentuk dan sokongan.','🦴'],['move','Otot dan sendi bergerak','Anggota boleh bergerak.','💪'],['breathe','Peparu mengambil oksigen','Oksigen tersedia.','🫁'],['circulate','Jantung mengedarkan darah','Bahan dibawa ke badan.','🫀']),'🧍')
 ]);
 u('animals','Haiwan','🐾','Siasat perlindungan, kemandirian dan hubungan makanan.',[
  q('Cara Haiwan Melindungi Diri','animals5','classify','Padankan ciri perlindungan dengan haiwan.','Periksa cangkerang, duri dan penyamaran.','Haiwan mempunyai ciri dan tingkah laku berlainan untuk melindungi diri daripada musuh.',cls(['shell','Kura-kura: cangkerang','body','Cangkerang keras melindungi badan.','🐢'],['spine','Landak: duri','body','Duri menyukarkan musuh mendekati.','🦔'],['camouflage','Belalang daun: penyamaran','behavior','Warna dan bentuk membantu tersembunyi.','🦗']),'🛡️'),
  q('Kemandirian Spesies','animals5','classify','Kenal pasti cara haiwan memastikan anak terus hidup.','Bandingkan telur banyak, telur bercangkerang dan penjagaan anak.','Haiwan memastikan kemandirian spesies melalui pembiakan, perlindungan telur atau anak dan penjagaan yang sesuai.',cls(['many','Katak menghasilkan banyak telur','many','Bilangan banyak meningkatkan peluang ada yang hidup.','🐸'],['nest','Burung menjaga sarang','care','Induk melindungi dan memberi makan anak.','🐦'],['pouch','Kanggaru membawa anak','care','Anak dilindungi dalam kantung.','🦘']),'🐣'),
  q('Anak Dijaga atau Tidak?','animals5','classify','Bandingkan haiwan yang menjaga anak dan yang kurang penjagaan.','Periksa bukti sarang, makanan dan perlindungan.','Sesetengah haiwan menjaga anak dengan aktif, manakala yang lain menghasilkan banyak telur atau anak dengan penjagaan yang sedikit.',cls(['bird','Burung memberi makan anak','care','Anak dijaga di sarang.','🐦'],['cat','Kucing menyusukan anak','care','Induk memberi makanan dan perlindungan.','🐈'],['frog','Katak meninggalkan banyak telur','little','Telur banyak tetapi penjagaan sedikit.','🐸']),'🔎'),
  q('Rantai Makanan','food5','sequence','Bina satu rantai makanan mudah.','Susun sumber tenaga, pengeluar dan pengguna mengikut arah pemindahan makanan.','Rantai makanan menunjukkan hubungan makanan dan pemindahan tenaga daripada Matahari kepada pengeluar dan pengguna.',seq(['sun','Matahari','Sumber tenaga bagi tumbuhan.','☀️'],['grass','Rumput','Pengeluar membuat makanan.','🌱'],['grasshopper','Belalang','Pengguna memakan rumput.','🦗'],['frog','Katak','Katak memakan belalang.','🐸']),'🔗'),
  q('Jaringan Makanan','food-web5','network','Bina beberapa rantai yang saling berkait.','Sambungkan tumbuhan kepada pengguna yang betul sehingga semua hubungan lengkap.','Jaringan makanan terdiri daripada beberapa rantai makanan yang saling berkait; perubahan satu populasi boleh mempengaruhi yang lain.',seq(['plant-rabbit','Tumbuhan → arnab','Arnab memakan tumbuhan.','🌿→🐇'],['plant-grasshopper','Tumbuhan → belalang','Belalang memakan tumbuhan.','🌿→🦗'],['grasshopper-frog','Belalang → katak','Katak memakan belalang.','🦗→🐸'],['rabbit-eagle','Arnab → helang','Helang boleh memakan arnab.','🐇→🦅'],['frog-eagle','Katak → helang','Helang boleh memakan katak.','🐸→🦅']),'🕸️')
 ]);
 u('plants','Tumbuhan','🌾','Terokai perlindungan dan pencaran biji benih.',[
  q('Cara Tumbuhan Melindungi Diri','plants5','classify','Padankan ciri tumbuhan dengan fungsi perlindungan.','Periksa duri, getah dan bau.','Tumbuhan boleh mempunyai duri, getah, bulu halus atau bau untuk melindungi diri daripada musuh.',cls(['thorn','Pokok berduri','physical','Duri menyukarkan haiwan memakannya.','🌵'],['latex','Getah melekit','chemical','Getah boleh menghalang gangguan.','💧'],['smell','Bau kuat','chemical','Bau boleh menghindarkan sesetengah haiwan.','🌿']),'🛡️'),
  q('Kemandirian Tumbuhan','plants5','classify','Kenal pasti penyesuaian kepada keadaan persekitaran.','Bandingkan kaktus, pokok bakau dan pokok memanjat.','Ciri khas membantu tumbuhan mendapatkan air, cahaya atau kestabilan untuk terus hidup.',cls(['cactus','Batang kaktus menyimpan air','dry','Membantu hidup di tempat kering.','🌵'],['mangrove','Akar bakau menyokong','wet','Membantu di tanah lembut dan berair.','🌳'],['climber','Sulur memanjat','light','Membantu mencapai cahaya.','🌿']),'🌱'),
  q('Biji Benih Bergerak','dispersal5','compare','Perhatikan bagaimana bentuk mempengaruhi pergerakan biji.','Uji biji bersayap, terapung dan bercangkuk.','Ciri buah atau biji membantu pencaran melalui angin, air, haiwan atau mekanisme letupan.',seq(['wing','Uji biji bersayap','Biji berputar dan dibawa angin.','🍃'],['float','Uji buah terapung','Buah dibawa air.','🥥'],['hook','Uji biji bercangkuk','Biji melekat pada bulu haiwan.','🪝']),'🌬️'),
  q('Cara Pencaran','dispersal5','classify','Kelaskan contoh mengikut agen pencaran.','Periksa ciri setiap buah atau biji.','Angin, air, haiwan dan mekanisme letupan ialah cara pencaran yang membantu biji bergerak jauh daripada induk.',cls(['wing','Meranti bersayap','wind','Bentuk sayap dibawa angin.','🍃'],['coconut','Kelapa terapung','water','Sabut membantu terapung.','🥥'],['hook','Kemuncup bercangkuk','animal','Melekat pada bulu atau pakaian.','🪝'],['pod','Buah keembung pecah','explosive','Buah matang memencarkan biji apabila pecah.','💥']),'🌾'),
  q('Cabaran Pencaran Biji Benih','dispersal5','design','Pilih reka bentuk biji bagi empat persekitaran.','Padankan bentuk dengan angin, sungai, laluan haiwan atau buah yang pecah.','Reka bentuk pencaran sesuai dengan agen dan membantu mengurangkan persaingan berhampiran pokok induk.',cls(['light','Ringan dan bersayap','wind','Sesuai dibawa angin.','🍃'],['buoyant','Bersabut dan terapung','water','Sesuai dibawa air.','🌊'],['hooked','Bercangkuk','animal','Sesuai melekat pada haiwan.','🐾'],['pod','Lenggai anjal','explosive','Sesuai memencar apabila pecah.','💥']),'🧑‍🔬')
 ]);
 u('electricity','Elektrik','🔋','Bandingkan sumber serta litar bersiri dan selari dengan selamat.',[
  q('Dari Mana Elektrik Datang?','circuit5','classify','Kenal pasti sumber tenaga elektrik yang sesuai.','Periksa bateri, sel suria, dinamo dan soket rumah secara maya.','Bateri, sel suria dan generator boleh membekalkan tenaga elektrik; elektrik rumah mesti digunakan dengan pengawasan orang dewasa.',cls(['battery','Bateri lampu suluh','portable','Sumber mudah alih.','🔋'],['solar','Sel suria','renewable','Menukar tenaga cahaya kepada elektrik.','☀️'],['generator','Generator','generated','Menukar gerakan kepada elektrik.','⚙️'],['socket','Soket rumah','mains','Bekalan utama; jangan disentuh atau diuji oleh kanak-kanak.','🔌']),'⚡'),
  q('Litar Bersiri','advanced-circuit','series','Bina laluan tunggal untuk dua mentol.','Sambungkan bateri, dua mentol dan suis dalam satu laluan tertutup.','Dalam litar bersiri, komponen berada pada satu laluan; jika satu mentol terputus, kedua-duanya padam.',seq(['battery','Sambung bateri','Sumber disediakan.','🔋'],['bulb1','Sambung mentol 1','Mentol pertama pada laluan.','💡'],['bulb2','Sambung mentol 2','Mentol kedua pada laluan sama.','💡'],['switch','Tutup suis','Laluan lengkap dan kedua-dua mentol menyala.','🔘'],['remove','Uji satu mentol terputus','Laluan terbuka dan kedua-duanya padam.','✖']),'🔌'),
  q('Litar Selari','advanced-circuit','parallel','Bina dua cabang untuk dua mentol.','Sambungkan setiap mentol pada cabang tersendiri.','Dalam litar selari, terdapat lebih daripada satu laluan; satu cabang boleh berfungsi apabila cabang lain terbuka.',seq(['source','Sambung bateri','Sumber membekalkan litar.','🔋'],['branch','Bina dua cabang','Dua laluan diwujudkan.','⑂'],['bulb1','Sambung mentol cabang 1','Cabang pertama lengkap.','💡'],['bulb2','Sambung mentol cabang 2','Cabang kedua lengkap.','💡'],['test','Buka satu cabang','Mentol pada cabang lain kekal menyala.','✅']),'⚡'),
  q('Bandingkan Kecerahan','advanced-circuit','compare','Bandingkan dua mentol serupa dalam model bersiri dan selari.','Aktifkan kedua-dua model dengan sumber yang sama.','Dalam model asas ini, mentol serupa dalam litar selari kelihatan lebih cerah berbanding dua mentol dalam litar bersiri.',seq(['series','Aktifkan litar bersiri','Dua mentol berkongsi satu laluan dan kelihatan lebih malap.','💡'],['parallel','Aktifkan litar selari','Setiap cabang menerima bekalan daripada sumber dan kelihatan lebih cerah.','💡'],['record','Rekod perbandingan','Keadaan komponen dan sumber dikekalkan sama.','📋']),'🔆'),
  q('Jurutera Litar','advanced-circuit','design','Reka lampu bilik yang terus berfungsi jika satu mentol rosak.','Pilih cabang selari, suis dan amalan selamat.','Litar selari sesuai apabila mentol perlu berfungsi secara bebas; gunakan komponen voltan rendah maya dan matikan suis apabila tidak digunakan.',cls(['parallel','Gunakan dua cabang selari','yes','Setiap mentol mempunyai laluan sendiri.','⑂'],['switch','Tambah suis kawalan','yes','Suis mengawal litar dan menjimatkan tenaga.','🔘'],['series','Satu laluan bersiri','no','Satu putus memadamkan semua mentol.','➖'],['mains','Uji soket rumah sebenar','no','Tidak selamat; aktiviti kekal maya.','⚠️']),'🧰')
 ]);
 u('heat','Haba','🌡️','Bandingkan pemindahan haba, suhu, pengembangan dan pengecutan.',[
  q('Panas dan Sejuk','heat5','compare','Jejak pemindahan haba antara dua objek.','Sentuhkan sudu suhu bilik pada air suam maya.','Haba berpindah daripada objek bersuhu lebih tinggi kepada objek bersuhu lebih rendah sehingga perbezaan berkurang.',seq(['water','Periksa air: 60°C','Air mempunyai suhu lebih tinggi.','60°'],['spoon','Periksa sudu: 25°C','Sudu mempunyai suhu lebih rendah.','25°'],['contact','Sentuhkan secara maya','Haba berpindah dari air ke sudu.','↔']),'♨️'),
  q('Suhu Berubah','heat5','measure','Ukur perubahan suhu dengan skala Celsius.','Panaskan air maya dan baca termometer pada tiga masa.','Suhu ialah ukuran darjah kepanasan; haba yang diterima boleh meningkatkan suhu air.',seq(['start','Baca 25°C','Bacaan awal direkod dalam darjah Celsius.','25°C'],['middle','Baca 40°C','Suhu meningkat selepas menerima haba.','40°C'],['end','Baca 55°C','Suhu terus meningkat dalam simulasi.','55°C']),'🌡️'),
  q('Mengembang Apabila Panas','heat5','investigate','Perhatikan perubahan saiz pepejal apabila dipanaskan.','Uji bola logam maya melalui gelang sebelum dan selepas pemanasan.','Kebanyakan bahan mengembang apabila dipanaskan; model bola menjadi sedikit lebih besar.',seq(['cold','Uji bola pada suhu bilik','Bola melepasi gelang.','⚪'],['heat','Panaskan secara maya','Saiz bola meningkat sedikit.','♨️'],['test','Uji semula','Bola model tidak lagi melepasi gelang.','⭕']),'🔬'),
  q('Mengecut Apabila Sejuk','heat5','investigate','Perhatikan pengecutan selepas penyejukan.','Sejukkan bola logam maya dan uji semula.','Kebanyakan bahan mengecut apabila disejukkan; model bola kembali lebih kecil.',seq(['hot','Periksa bola panas','Bola model mengembang.','🔴'],['cool','Sejukkan secara maya','Suhu menurun.','❄️'],['test','Uji pada gelang','Bola mengecut dan boleh melepasi gelang.','⚪']),'🧊'),
  q('Cabaran Haba','heat5','design','Gunakan pengembangan dan penebatan untuk menyelesaikan masalah.','Pilih celah jambatan, pemegang penebat dan termometer.','Jurutera menyediakan ruang untuk pengembangan, menggunakan penebat untuk mengurangkan pemindahan haba dan mengukur suhu dengan termometer.',cls(['gap','Sediakan celah pengembangan','yes','Membenarkan bahan mengembang dengan selamat.','↔'],['handle','Gunakan pemegang penebat','yes','Mengurangkan pemindahan haba ke tangan.','🧤'],['thermometer','Ukur dengan termometer','yes','Memberi bacaan °C.','🌡️'],['touch','Sentuh objek panas','no','Tidak selamat.','⚠️']),'🏗️')
 ]);
 u('rust','Pengaratan','🧲','Jalankan eksperimen maya tentang sebab dan pencegahan karat.',[
  q('Kenali Karat','rust5','classify','Kenal pasti objek yang boleh berkarat.','Periksa bahan setiap objek.','Pengaratan berlaku pada objek yang mengandungi besi; plastik, kaca dan kayu tidak berkarat.',cls(['nail','Paku besi','rusts','Mengandungi besi.','🔩'],['can','Tin keluli','rusts','Keluli mengandungi besi.','🥫'],['plastic','Sudu plastik','not','Tidak mengandungi besi.','🥄'],['glass','Gelas kaca','not','Kaca tidak berkarat.','🥛']),'🟤'),
  q('Apa Menyebabkan Karat?','rust5','compare','Bandingkan paku dengan udara dan air.','Sediakan tiga bekas maya dengan keadaan berbeza.','Besi berkarat apabila air dan udara hadir bersama; kadar boleh dipengaruhi keadaan persekitaran.',seq(['dry','Paku dengan udara kering','Tiada air: karat tidak terbentuk dalam model.','🏜️'],['water-no-air','Paku dalam air tanpa udara','Udara disingkirkan: karat tidak terbentuk dalam model.','💧'],['air-water','Paku dengan udara dan air','Karat terbentuk.','🟤']),'🧪'),
  q('Uji Paku','rust5','fair-test','Sediakan ujian adil bagi keadaan pengaratan.','Gunakan paku sama, masa sama dan ubah keadaan air/udara sahaja.','Ujian adil menunjukkan air dan udara diperlukan untuk pengaratan besi dalam model ini.',seq(['same','Pilih paku sama','Jenis dan saiz paku dikawal.','🔩'],['time','Tetapkan masa sama','Tempoh dikawal.','⏱️'],['conditions','Ubah air dan udara','Keadaan dimanipulasikan.','💧'],['observe','Bandingkan karat','Jumlah karat ialah hasil pemerhatian.','🔎']),'⚖️'),
  q('Cegah Pengaratan','rust5','classify','Pilih kaedah yang menghalang air dan udara.','Periksa cat, minyak, salutan dan calar terbuka.','Cat, minyak atau salutan pelindung boleh mengurangkan pengaratan dengan menghalang air dan udara daripada mencapai besi.',cls(['paint','Cat permukaan','yes','Membentuk lapisan pelindung.','🎨'],['oil','Sapu minyak pada mesin','yes','Menghalang air dan udara pada permukaan.','🛢️'],['coat','Gunakan salutan sesuai','yes','Melindungi besi.','🛡️'],['scratch','Biarkan calar terbuka','no','Permukaan terdedah boleh berkarat.','✖']),'🛡️'),
  q('Selamatkan Peralatan','rust5','sequence','Baiki peralatan besi secara maya dan cegah karat kembali.','Periksa, bersihkan secara maya dan lindungi permukaan.','Pencegahan pengaratan memerlukan permukaan diperiksa dan dilindungi semula apabila salutan rosak.',seq(['inspect','Cari bahagian terdedah','Calar dikenal pasti.','🔎'],['clean','Bersihkan secara maya','Permukaan disediakan tanpa bahan kimia sebenar.','🧽'],['coat','Sapukan salutan maya','Air dan udara dihalang.','🎨'],['store','Simpan di tempat kering','Pendedahan air dikurangkan.','🏠']),'🧰')
 ]);
 u('matter','Jirim','🧊','Siasat keadaan jirim dan perubahan keadaan air.',[
  q('Pepejal, Cecair atau Gas?','matter5','classify','Kelaskan contoh kepada tiga keadaan jirim.','Periksa bentuk dan ruang yang dipenuhi.','Pepejal mempunyai bentuk tetap, cecair mengikut bentuk bekas dan gas memenuhi ruang yang tersedia.',cls(['ice','Ais','solid','Mempunyai bentuk tetap.','🧊'],['water','Air','liquid','Mengikut bentuk bekas.','💧'],['steam','Wap air','gas','Merebak memenuhi ruang.','☁️']),'🧪'),
  q('Sifat Jirim','matter5','classify','Padankan sifat dengan keadaan jirim.','Uji bentuk, isipadu dan kebolehan memenuhi bekas secara maya.','Setiap keadaan jirim mempunyai sifat yang boleh diperhatikan tanpa menggunakan teori zarah lanjutan.',cls(['block','Bentuk kekal','solid','Ciri pepejal.','◼️'],['pour','Boleh dituang, isipadu tetap','liquid','Ciri cecair.','💧'],['fill','Memenuhi seluruh bekas','gas','Ciri gas.','☁️']),'📦'),
  q('Perubahan Keadaan','matter5','sequence','Jejak peleburan, pembekuan, penyejatan dan kondensasi.','Panaskan dan sejukkan air maya mengikut urutan.','Pemanasan boleh menyebabkan peleburan dan penyejatan; penyejukan boleh menyebabkan kondensasi dan pembekuan.',seq(['melt','Ais melebur menjadi air','Pepejal menerima haba dan menjadi cecair.','🧊→💧'],['evaporate','Air menyejat','Cecair menerima haba dan menjadi gas.','💧→☁️'],['condense','Wap terkondensasi','Gas kehilangan haba dan menjadi cecair.','☁️→💧'],['freeze','Air membeku','Cecair kehilangan haba dan menjadi pepejal.','💧→🧊']),'♻️'),
  q('Kitaran Air Mini','matter5','sequence','Bina model kitaran perubahan keadaan air.','Aktifkan penyejatan, kondensasi dan pengumpulan.','Dalam kitaran air mini, air menyejat, wap terkondensasi menjadi titisan dan air terkumpul semula.',seq(['heat','Panaskan air dengan Matahari maya','Air menerima haba.','☀️'],['evaporate','Air menyejat','Wap air naik.','☁️'],['condense','Sejukkan penutup','Titisan terbentuk.','💧'],['collect','Kumpulkan titisan','Air kembali sebagai cecair.','🥣']),'🌧️'),
  q('Cabaran Jirim','matter5','diagnose','Kenal pasti perubahan keadaan dalam situasi harian.','Periksa ais cair, cermin berkabus dan air beku.','Perubahan keadaan boleh dikenal pasti melalui keadaan awal, keadaan akhir dan sama ada haba diterima atau dibebaskan.',cls(['ice','Ais krim mencair','melt','Pepejal menjadi cecair.','🍦'],['mirror','Titisan pada cermin sejuk','condense','Wap air menjadi cecair.','🪞'],['tray','Air dalam peti sejuk beku','freeze','Cecair menjadi pepejal.','🧊'],['puddle','Lopak semakin kering','evaporate','Cecair menjadi gas.','☀️']),'🔍')
 ]);
 u('moon-constellations','Fasa Bulan dan Buruj','🌙','Modelkan fasa Bulan dan gunakan corak buruj.',[
  q('Bentuk Bulan Berubah','moon5','compare','Bandingkan bahagian Bulan yang diterangi dari Bumi.','Gerakkan Bulan pada empat kedudukan model.','Bulan tidak berubah bentuk; bahagian terang yang kelihatan dari Bumi berubah apabila Bulan mengelilingi Bumi.',seq(['new','Bulan baharu','Bahagian terang menghadap jauh daripada pemerhati Bumi.','🌑'],['quarter','Suku pertama','Separuh cakera kelihatan terang.','🌓'],['full','Bulan purnama','Bahagian menghadap Bumi kelihatan terang.','🌕'],['last','Suku akhir','Separuh bertentangan kelihatan terang.','🌗']),'🌙'),
  q('Susun Fasa Bulan','moon5','sequence','Susun lapan fasa mengikut pola.','Pilih fasa bermula daripada Bulan baharu.','Fasa Bulan berulang dalam urutan apabila kedudukan Bulan berubah relatif kepada Bumi dan Matahari.',seq(['new','Bulan baharu','Permulaan urutan model.','🌑'],['wax-crescent','Sabit muda','Bahagian terang kelihatan bertambah.','🌒'],['first','Suku pertama','Separuh terang.','🌓'],['wax-gibbous','Hampir purnama','Bahagian terang terus bertambah.','🌔'],['full','Purnama','Cakera terang penuh kelihatan.','🌕'],['wane-gibbous','Selepas purnama','Bahagian terang mula berkurang.','🌖'],['last','Suku akhir','Separuh terang bertentangan.','🌗'],['wane-crescent','Sabit tua','Bahagian terang semakin kecil.','🌘']),'🌙'),
  q('Bulan Mengelilingi Bumi','moon5','orbit','Gerakkan Bulan mengelilingi Bumi dan jejak fasa.','Majukan model satu kedudukan pada satu masa.','Bulan mengelilingi Bumi; kedudukan relatif Bulan, Bumi dan Matahari menghasilkan pola fasa yang diperhatikan.',seq(['p1','Kedudukan 1','Bulan baharu.','①'],['p2','Kedudukan 2','Suku pertama.','②'],['p3','Kedudukan 3','Purnama.','③'],['p4','Kedudukan 4','Suku akhir.','④'],['cycle','Lengkapkan kitaran','Pola kembali ke permulaan.','↻']),'🌍'),
  q('Kenali Buruj','constellation5','classify','Padankan corak bintang ringkas dengan nama buruj.','Sambungkan titik dan bandingkan bentuk pendidikan.','Buruj ialah corak bintang yang kelihatan dari Bumi; corak dipermudah untuk membantu pengenalan.',cls(['orion','Belantik (Orion)','orion','Tiga bintang sebaris menjadi petunjuk.','✦✦✦'],['scorpion','Skorpio','scorpion','Corak melengkung seperti kala jengking.','〰️✦'],['dipper','Biduk','dipper','Corak seperti pencedok.','✦⌞✦'],['cross','Pari','cross','Empat bintang utama membentuk corak seperti layang-layang.','✦◇✦']),'✨'),
  q('Navigasi Dengan Buruj','constellation5','sequence','Gunakan buruj sebagai petunjuk arah pada model langit.','Cari buruj, kenal pasti arah dan semak dengan kompas maya.','Buruj tertentu boleh digunakan sebagai petunjuk arah, tetapi kedudukan dan keterlihatannya bergantung pada tempat, masa dan cuaca.',seq(['locate','Cari corak buruj','Corak dikenal pasti.','✨'],['direction','Tarik garis panduan','Arah anggaran ditunjukkan.','🧭'],['verify','Semak kompas maya','Arah disahkan dengan alat.','✅']),'🧭')
 ]);
 u('machines','Mesin','⚙️','Gabungkan mesin ringkas dan mekanisme untuk menyelesaikan masalah.',[
  q('Mesin Ringkas Di Sekeliling Kita','machines5','classify','Kenal pasti mesin ringkas dalam alat harian.','Periksa pembuka botol, tangga, skru dan tombol.','Mesin ringkas membantu mengubah arah atau magnitud daya dan menjadikan kerja lebih mudah.',cls(['opener','Pembuka botol','lever','Menggunakan prinsip tuas.','🧰'],['stairs','Tangga','inclined','Satah condong membantu naik beransur-ansur.','🪜'],['screw','Skru','screw','Satah condong berlingkar.','🔩'],['knob','Tombol pintu','wheel','Roda dan gandar membantu memutar.','🚪']),'⚙️'),
  q('Gear Bergerak','gears5','investigate','Perhatikan arah dan kelajuan gear bersambung.','Putar gear pemacu dan bandingkan gear kecil serta besar.','Gear bersentuhan berputar dalam arah bertentangan; saiz gear mempengaruhi bilangan putaran dalam model.',seq(['driver','Putar gear pemacu','Gear pertama bergerak.','⚙️'],['mesh','Sambungkan gear kedua','Arah gear kedua bertentangan.','⚙️'],['small','Bandingkan gear kecil','Gear kecil membuat lebih banyak putaran.','⚙️'],['large','Bandingkan gear besar','Gear besar membuat lebih sedikit putaran.','⚙️']),'⚙️'),
  q('Gabungkan Mesin','machines5','sequence','Gabungkan beberapa mesin ringkas menjadi mekanisme.','Bina troli pengangkat maya tanpa mengulang eksperimen takal atau tuas.','Mesin kompleks menggabungkan mesin ringkas supaya beberapa fungsi bekerja bersama.',seq(['wheel','Tambah roda dan gandar','Troli boleh bergerak.','🛞'],['ramp','Tambah satah condong','Beban boleh dinaikkan beransur-ansur.','📐'],['screw','Tambah skru pengikat','Bahagian dipasang kukuh.','🔩'],['gear','Tambah gear pemacu','Gerakan dipindahkan.','⚙️']),'🏗️'),
  q('Pilih Mesin Sesuai','machines5','design','Pilih mekanisme mengikut masalah praktikal.','Padankan alat dengan kerja yang perlu dilakukan.','Pemilihan mesin bergantung pada fungsi, keselamatan dan kerja yang hendak dipermudah.',cls(['ramp','Tolak kotak ke atas: tanjakan','yes','Memberi laluan condong.','📦'],['gear','Pindah gerakan putaran: gear','yes','Gear memindahkan gerakan.','⚙️'],['wheel','Gerakkan troli: roda dan gandar','yes','Membantu pergerakan.','🛞'],['knife','Angkat troli: pisau','no','Baji tidak sesuai untuk tugas itu.','🔪']),'🧰'),
  q('Cabaran Reka Mesin','machines5','sequence','Reka penghantar kotak menggunakan gabungan mekanisme.','Pilih asas bergerak, gear, pengikat dan uji reka bentuk.','Reka bentuk mesin yang baik menggabungkan komponen sesuai, diuji dan diperbaiki untuk melakukan kerja dengan selamat.',seq(['base','Tambah roda dan gandar','Asas boleh bergerak.','🛞'],['drive','Tambah gear pemacu','Gerakan dipindahkan.','⚙️'],['fasten','Pasang skru pengikat','Struktur stabil.','🔩'],['guard','Tambah penghadang keselamatan','Bahagian bergerak dilindungi.','🛡️'],['test','Uji dan baiki','Kotak bergerak ke destinasi.','✅']),'👷')
 ]);
})();
