'use strict';
(()=>{const D=window.MakmalYear1Domains,ui=window.MakmalYear1UI,b=ui.button;
 const sequential={init(){},solved:(s,d)=>Object.keys(s.done).length===d.actions.length,act(s,d,a,v){if(a!=='do')return;const next=d.actions[Object.keys(s.done).length];if(next?.id===v){s.done[v]=true;ui.message(s,next.note);s.effect='observation';}else ui.message(s,'Tekan butang yang seterusnya.',false);},hint(s,d){const x=d.actions[Object.keys(s.done).length];return x?['do',x.id,'Cuba '+x.label+'.']:['next',undefined,'Semua sudah siap.'];},render(s,d,active){return ui.scene(d,s)+`<div class="y1-action-grid">${d.actions.map((x,i)=>`<button class="y1-action" data-exp="do" data-value="${x.id}" ${!active||s.done[x.id]?'disabled':''}><span>${ui.art(x.art)}<strong>${x.label}</strong></span><small>${s.done[x.id]?'✓ '+x.note:i===Object.keys(s.done).length?'Tindakan seterusnya':'Belum diuji'}</small></button>`).join('')}</div>`;}};
 const checklist={...sequential,act(s,d,a,v){if(a==='do'&&d.actions.some(x=>x.id===v)&&!s.done[v]){s.done[v]=true;ui.message(s,d.actions.find(x=>x.id===v).note);s.effect='observation';}},hint(s,d){const x=d.actions.find(x=>!s.done[x.id]);return x?['do',x.id,'Cuba '+x.label+'.']:['next',undefined,'Semua sudah siap.'];}};
 ['sequence','compare','investigate','measure','model','simulate'].forEach(mode=>D[mode]=sequential);D.checklist=checklist;
 function label(id){return ({evidence:'Pemerhatian',assumption:'Teka-teki',sound:'Ada bunyi',silent:'Tiada bunyi',soft:'Lembut',rough:'Kasar',guess:'Teka-teki',safe:'Selamat',unsafe:'Tidak selamat',living:'Benda hidup',nonliving:'Bukan hidup',need:'Perlu',notneed:'Tidak perlu',see:'Mata',hear:'Telinga',touch:'Kulit',fly:'Terbang',swim:'Berenang',eat:'Makan',fish:'Ikan',bird:'Burung',turtle:'Kura-kura',long:'Panjang',wide:'Lebar',water:'Serap air',support:'Sokong',food:'Buat makanan',yes:'Ditarik',no:'Tidak ditarik',absorb:'Menyerap',not:'Tidak menyerap',high:'Tanah tinggi',low:'Tanah rendah',base:'Tapak rata',roll:'Boleh bergolek',assumption:'Andaian',increase:'Meningkat',same:'Dimalarkan',responding:'Bergerak balas',manipulated:'Dimanipulasikan',yes:'Sesuai / selamat',no:'Tidak sesuai',useful:'Berguna',harmful:'Memudaratkan',living:'Proses hidup',notliving:'Bukan bukti hidup',group:'Berkumpulan',solitary:'Bersendirian',animal:'Haiwan',plant:'Tumbuhan',mutualism:'Saling mendapat manfaat',commensalism:'Satu mendapat manfaat',parasitism:'Parasit mendapat manfaat',extinct:'Pupus',threatened:'Terancam',protect:'Lindungi habitat',push:'Tolak',pull:'Tarik',more:'Geseran lebih banyak',less:'Geseran lebih sedikit',distance:'Jarak',time:'Masa',speed:'Kelajuan',drying:'Pengeringan',cold:'Penyejukan',salt:'Pengasinan',bottle:'Pengetinan / pembotolan',biodegradable:'Terbiodegradasi',nonbio:'Tidak terbiodegradasi',reduce:'Kurangkan',reuse:'Guna semula',recycle:'Kitar semula',solar:'Gerhana Matahari',lunar:'Gerhana Bulan',north:'Arah utara',season:'Corak bermusim',component:'Komponen mesin',improve:'Baiki reka bentuk'})[id]||id.replaceAll('-',' ');}
 const classify={init(){},solved:(s,d)=>Object.keys(s.matched).length===d.actions.length,act(s,d,a,v){if(a==='choose'&&d.actions.some(x=>x.id===v)&&!s.matched[v]){s.selected=v;s.message='Lihat gambar dahulu.';}if(a==='inspect'&&s.selected){s.inspected[s.selected]=true;s.message=d.actions.find(x=>x.id===s.selected).note;s.effect='observation';}if(a==='assign'&&s.selected&&s.inspected[s.selected]){const x=d.actions.find(x=>x.id===s.selected);if(x.target===v){s.matched[x.id]=v;s.selected=null;ui.message(s,'✓ Betul!');s.effect='classification';}else ui.message(s,'Cuba pilihan lain.',false);}},hint(s,d){const x=d.actions.find(x=>x.id===s.selected)||d.actions.find(x=>!s.matched[x.id]);if(!s.selected)return ['choose',x.id,'Pilih '+x.label+'.'];if(!s.inspected[x.id])return ['inspect',undefined,'Lihat petunjuk.'];return ['assign',x.target,'Pilih kumpulan yang sepadan.'];},render(s,d,active){const x=d.actions.find(x=>x.id===s.selected),targets=[...new Set(d.actions.map(x=>x.target))];return ui.scene(d,s)+`<div class="y1-cards">${d.actions.map(x=>`<button class="y1-card" data-exp="choose" data-value="${x.id}" aria-pressed="${s.selected===x.id}" ${!active||s.matched[x.id]?'disabled':''}>${ui.art(x.art)}<strong>${x.label}</strong><small>${s.matched[x.id]?'✓ '+label(x.target):'Pilih dan lihat'}</small></button>`).join('')}</div>${x?`<section class="y1-evidence"><strong>${x.label}</strong>${b('inspect',undefined,'🔎 Periksa bukti',!active||s.inspected[x.id])}<p>${s.inspected[x.id]?x.note:'Belum dilihat.'}</p></section>`:''}<div class="y1-targets">${targets.map(t=>b('assign',t,label(t),!active||!x||!s.inspected[x.id])).join('')}</div>`;}};
 ['classify','select','evaluate','diagnose','design'].forEach(mode=>D[mode]=classify);
 ['inquiry1','microbe6','ecology1','conservation6','force6','speed6','preservation6','waste6','eclipse6','constellation6','machines6'].forEach(mode=>D[mode]=sequential);
})();
