'use strict';
(()=>{const Y=window.MakmalYear6;
 const u=(id,title,icon,description,missions)=>Y.addUnit({id,title,icon,description,totalMissions:5},missions);
 const q=(title,domain,mode,objective,instruction,discovery,actions,scene)=>({title,domain,mode,objective,instruction,discovery,scene,observations:[discovery,'Bukti pada model menyokong kesimpulan ini.'],question:'Apakah kesimpulan yang paling disokong oleh bukti?',answers:[discovery,'Andaian awal sentiasa dianggap benar.'],actions});
 const seq=(...x)=>x.map(([id,label,note,art])=>({id,label,note,art}));
 const cls=(...x)=>x.map(([id,label,target,note,art])=>({id,label,target,note,art}));
 u('science-skills','Kemahiran Saintifik','🔬','Nilai bukti, tafsir data dan rancang penyiasatan adil.',[
  q('Bukti atau Andaian?','inquiry6','classify','Bezakan pemerhatian daripada andaian.','Periksa setiap pernyataan sebelum mengelaskannya.', 'Bukti datang daripada pemerhatian atau ukuran; andaian perlu diuji.',cls(['mass','Jisim objek ialah 120 g','evidence','Bacaan diukur dengan alat.','⚖️'],['cold','Objek ini pasti paling sejuk','assumption','Tiada ukuran suhu diberikan.','💭'],['drops','Terdapat lima titisan','evidence','Bilangan boleh diperhatikan.','💧']),'🔎'),
  q('Tafsir Corak Data','inquiry6','sequence','Tafsir pola dalam jadual pertumbuhan.','Susun bacaan kemudian nyatakan pola berdasarkan data.','Data menunjukkan pertambahan tetap 3 cm setiap minggu dalam penyiasatan ini.',seq(['w1','Minggu 1: 3 cm','Bacaan awal.','3'],['w2','Minggu 2: 6 cm','Bertambah 3 cm.','6'],['w3','Minggu 3: 9 cm','Pola diteruskan.','9'],['infer','Nyatakan pola +3 cm','Tafsiran merujuk semua bacaan.','📈']),'📊'),
  q('Tentukan Pemboleh Ubah','inquiry6','classify','Kenal pasti pemboleh ubah ujian penyejatan.','Kelaskan luas permukaan, masa penyejatan dan isi padu air.','Ujian adil mengubah luas permukaan, mengukur masa dan mengekalkan isi padu serta suhu awal.',cls(['area','Luas permukaan bekas','manipulated','Faktor ini sengaja diubah.','↔'],['time','Masa air tersejat','responding','Hasil ini diukur.','⏱️'],['volume','Isi padu dan suhu awal','same','Faktor ini dikekalkan.','💧']),'⚗️'),
  q('Rancang Penyiasatan','inquiry6','sequence','Rancang ujian adil daripada soalan hingga data.','Susun hipotesis, kawalan, ukuran dan rekod.','Penyiasatan adil menguji satu pemboleh ubah dan menggunakan ukuran yang boleh dibandingkan.',seq(['question','Tetapkan soalan','Soalan boleh diuji.','❓'],['hypothesis','Bina hipotesis','Hubungan pemboleh ubah diramal.','💭'],['control','Kekalkan faktor lain','Perbandingan menjadi adil.','⚖️'],['measure','Ukur dan rekod','Data dikumpulkan.','📋']),'🧪'),
  q('Cabaran Saintis Tahun 6','inquiry6','sequence','Lengkapkan penyiasatan ringkas daripada soalan kepada kesimpulan.','Uji dua model kapal kertas dengan keadaan sama.','Kesimpulan sah menjawab soalan dengan merujuk data dan batas penyiasatan.',seq(['plan','Rancang ujian','Satu ciri kapal diubah.','📝'],['test','Uji kedua-dua model','Keadaan lain sama.','⛵'],['record','Rekod beban maksimum','Definisi operasi dinyatakan.','⚖️'],['compare','Banding data','Pola dikenal pasti.','📊'],['conclude','Buat kesimpulan','Kesimpulan merujuk bukti.','✅']),'🏅')
 ]);
 u('microorganisms','Mikroorganisma','🦠','Perhatikan mikroorganisma secara maya dengan selamat.',[
  q('Dunia Yang Terlalu Kecil','microbe6','sequence','Kenali contoh mikroorganisma melalui model maya.','Gunakan pembesaran maya pada sampel fiksyen.','Bakteria, fungi, protozoa dan sesetengah alga ialah mikroorganisma yang terlalu kecil untuk dilihat jelas tanpa bantuan.',seq(['sample','Pilih sampel maya','Sampel ini tidak disentuh atau dikultur.','🧫'],['zoom','Besarkan imej','Struktur menjadi kelihatan dalam model.','🔬'],['compare','Banding bentuk','Mikroorganisma mempunyai bentuk berbeza.','🦠']),'🔬'),
  q('Mikroorganisma Hidup','microbe6','classify','Kenal pasti bukti proses hidup mikroorganisma.','Periksa pertumbuhan, pembiakan dan gambar statik.','Pertumbuhan dan pembiakan dalam keadaan sesuai ialah bukti proses hidup mikroorganisma.',cls(['grow','Koloni maya bertambah','living','Pertumbuhan diperhatikan.','📈'],['reproduce','Bilangan sel bertambah','living','Pembiakan berlaku.','➗'],['shape','Imej hanya kelihatan bulat','notliving','Bentuk sahaja bukan bukti proses hidup.','⭕']),'🧫'),
  q('Baik atau Memudaratkan?','microbe6','classify','Nilai kesan mikroorganisma dalam situasi berbeza.','Kelaskan penggunaan dan kesan berdasarkan bukti.','Sesetengah mikroorganisma berguna, manakala sesetengahnya boleh menyebabkan penyakit atau merosakkan makanan.',cls(['yogurt','Bakteria membuat yogurt','useful','Digunakan dalam penghasilan makanan.','🥛'],['yeast','Yis menaikkan doh','useful','Menghasilkan gas dalam doh.','🍞'],['spoil','Mikroorganisma merosakkan makanan','harmful','Makanan menjadi tidak selamat.','⚠️']),'⚖️'),
  q('Makanan dan Mikroorganisma','microbe6','compare','Bandingkan perubahan makanan dalam suhu berbeza secara maya.','Perhatikan dua sampel fiksyen untuk tempoh sama.','Suhu dan keadaan penyimpanan boleh mempengaruhi pertumbuhan mikroorganisma dan kadar makanan rosak.',seq(['warm','Periksa sampel suhu bilik','Perubahan berlaku lebih cepat dalam model.','🌡️'],['cold','Periksa sampel sejuk','Perubahan lebih perlahan.','❄️'],['record','Banding pada masa sama','Perbandingan dibuat secara adil.','📋']),'🥣'),
  q('Kawal Pertumbuhan','microbe6','design','Pilih tindakan selamat untuk mengawal pertumbuhan mikroorganisma.','Nilai penyejukan, kebersihan dan kultur tidak diketahui.','Kebersihan, penyimpanan sesuai dan pemanasan terkawal industri membantu mengawal mikroorganisma; jangan kultur sampel tidak diketahui di rumah.',cls(['chill','Simpan makanan mudah rosak dengan sejuk','yes','Suhu rendah memperlahankan pertumbuhan banyak mikroorganisma.','❄️'],['clean','Gunakan peralatan bersih','yes','Mengurangkan pencemaran.','🧼'],['culture','Biak sampel tidak diketahui di rumah','no','Tidak selamat.','⛔']),'🛡️')
 ]);
 u('living-interactions','Interaksi Antara Hidupan','🌿','Siasat persaingan dan hubungan dalam ekosistem.',[
  q('Bersendirian atau Berkumpulan?','ecology6','classify','Bandingkan cara haiwan hidup.','Kelaskan situasi berdasarkan pemerhatian.','Sesetengah haiwan hidup berkumpulan untuk perlindungan atau kerjasama, manakala yang lain hidup bersendirian.',cls(['fish','Ikan berenang dalam kumpulan','group','Kumpulan membantu perlindungan.','🐟'],['lion','Singa memburu bersama','group','Ahli kumpulan bekerjasama.','🦁'],['tiger','Harimau dewasa mencari makanan sendiri','solitary','Kebanyakannya hidup bersendirian.','🐅']),'🐾'),
  q('Persaingan Haiwan','ecology6','compare','Kenal pasti sumber terhad yang menyebabkan persaingan.','Banding haiwan yang memerlukan makanan, air dan ruang sama.','Haiwan bersaing apabila sumber seperti makanan, air, pasangan atau ruang terhad.',seq(['food','Kurangkan makanan maya','Lebih banyak haiwan berebut sumber sama.','🍽️'],['water','Kurangkan air maya','Akses kepada air menjadi terhad.','💧'],['space','Kurangkan ruang','Tempat perlindungan menjadi terhad.','🏕️']),'⚖️'),
  q('Persaingan Tumbuhan','ecology6','investigate','Uji kesan kepadatan terhadap tumbuhan.','Bandingkan pasu dengan satu dan banyak anak pokok.','Tumbuhan boleh bersaing untuk cahaya, air, ruang dan nutrien apabila tumbuh rapat.',seq(['single','Periksa satu anak pokok','Sumber tersedia dengan lebih banyak.','🌱'],['crowded','Periksa pasu padat','Tumbuhan berkongsi sumber terhad.','🌿'],['compare','Banding pertumbuhan','Model padat menunjukkan pertumbuhan lebih lemah.','📏']),'🪴'),
  q('Hubungan Antara Spesies','ecology6','classify','Kenal pasti hubungan mudah antara spesies.','Periksa siapa mendapat manfaat dalam setiap situasi.','Interaksi boleh memberi manfaat kepada kedua-dua spesies, satu spesies sahaja, atau memudaratkan perumah.',cls(['bee','Lebah dan bunga','mutualism','Lebah mendapat makanan; bunga dibantu pendebungaan.','🐝'],['orchid','Orkid menumpang pada pokok','commensalism','Orkid mendapat sokongan tanpa mengambil makanan pokok.','🌸'],['tick','Sengkenit pada haiwan','parasitism','Parasit mendapat manfaat dan perumah dimudaratkan.','🔎']),'🔗'),
  q('Ekosistem Seimbang','ecology6','simulate','Modelkan kesan perubahan satu populasi.','Kurangkan tumbuhan, perhatikan herbivor, kemudian pemangsa.','Perubahan satu populasi atau sumber boleh mempengaruhi beberapa hidupan lain dalam ekosistem.',seq(['plants','Kurangkan tumbuhan','Makanan herbivor berkurang.','🌱'],['herbivore','Perhatikan herbivor','Populasi model menurun.','🐇'],['predator','Perhatikan pemangsa','Sumber makanan pemangsa turut berkurang.','🦅'],['restore','Pulihkan habitat','Sumber dan populasi boleh pulih secara beransur.','🌳']),'🌏')
 ]);
 u('conservation','Pemeliharaan dan Pemuliharaan','🐘','Nilai ancaman dan pilih tindakan melindungi spesies.',[
  q('Jejak Haiwan Pupus','conservation6','classify','Bezakan pupus daripada masih hidup.','Periksa rekod sejarah dan pemerhatian moden.','Spesies pupus tidak lagi mempunyai individu hidup; bukti sejarah membantu mengenal pastinya.',cls(['dodo','Dodo','extinct','Tiada individu hidup direkodkan.','🦤'],['tiger','Harimau Malaya','threatened','Masih hidup tetapi sangat terancam.','🐅'],['turtle','Penyu','threatened','Populasi tertentu menghadapi ancaman besar.','🐢']),'📚'),
  q('Siapa Terancam?','conservation6','evaluate','Kenal pasti organisma terancam berdasarkan bukti.','Bandingkan saiz populasi, habitat dan ancaman.','Spesies terancam mempunyai risiko kepupusan dan memerlukan tindakan berasaskan bukti.',cls(['tiger','Harimau Malaya: populasi kecil','threatened','Kehilangan habitat dan pemburuan mengancamnya.','🐅'],['rafflesia','Rafflesia: habitat khusus','threatened','Gangguan habitat menjejaskan kelangsungan.','🌺'],['dodo','Dodo: tiada rekod hidup','extinct','Spesies ini telah pupus.','🦤']),'🔎'),
  q('Mengapa Spesies Berkurang?','conservation6','classify','Hubungkan penurunan spesies dengan bukti ancaman.','Periksa kehilangan habitat, pencemaran dan pemburuan.','Kemusnahan habitat, pencemaran, perubahan sumber dan pemburuan boleh mengurangkan populasi.',cls(['forest','Hutan dibuka','protect','Habitat dan makanan hilang.','🪓'],['river','Sungai tercemar','protect','Kualiti habitat air menurun.','🏭'],['hunt','Pemburuan haram','protect','Individu dibuang daripada populasi.','⛔']),'⚠️'),
  q('Lindungi Habitat','conservation6','design','Pilih tindakan yang benar-benar melindungi habitat.','Nilai koridor hidupan liar, pemulihan sungai dan pembangunan tanpa kawalan.','Pemuliharaan melindungi habitat dan menggunakan sumber secara bertanggungjawab supaya spesies boleh terus hidup.',cls(['corridor','Bina koridor hidupan liar','yes','Menghubungkan habitat terpisah.','🌉'],['river','Pulihkan sungai','yes','Meningkatkan kualiti habitat.','💧'],['clear','Buka semua hutan','no','Memusnahkan habitat.','⛔']),'🌳'),
  q('Pelan Pemuliharaan','conservation6','sequence','Bina pelan berasaskan bukti untuk habitat Malaysia.','Kenal pasti ancaman, lindungi kawasan dan pantau hasil.','Pelan pemuliharaan yang baik menggabungkan perlindungan habitat, penguatkuasaan, pendidikan dan pemantauan.',seq(['survey','Kumpul data populasi','Keadaan awal diketahui.','📊'],['threat','Kenal pasti ancaman','Punca masalah ditentukan.','🔎'],['protect','Lindungi dan pulihkan habitat','Tindakan menyasar punca.','🌳'],['community','Libatkan komuniti','Tindakan lebih mampan.','🤝'],['monitor','Pantau perubahan','Keberkesanan dinilai.','📈']),'🗺️')
 ]);
 u('force','Daya','🧲','Uji tolakan, tarikan dan kesan geseran.',[
  q('Tolak atau Tarik?','force6','classify','Kelaskan tindakan sebagai tolakan atau tarikan.','Periksa arah tindakan pada objek.','Daya ialah tolakan atau tarikan yang boleh bertindak pada objek.',cls(['door','Menolak pintu','push','Daya menjauhi badan.','🚪'],['drawer','Membuka laci','pull','Daya menarik ke arah badan.','🗄️'],['cart','Menolak troli','push','Troli bergerak ke hadapan.','🛒']),'↔️'),
  q('Kesan Daya','force6','simulate','Perhatikan beberapa kesan daya.','Gunakan daya maya pada bola dan span.','Daya boleh mengubah gerakan, arah atau bentuk objek.',seq(['start','Tolak bola pegun','Bola mula bergerak.','⚽'],['direction','Tolak dari sisi','Arah bola berubah.','↪️'],['shape','Tekan span','Bentuk span berubah sementara.','🧽']),'🧪'),
  q('Geseran','force6','compare','Banding gerakan pada permukaan berbeza.','Gerakkan blok dengan daya awal sama.','Geseran menentang gerakan; permukaan berbeza menghasilkan geseran berbeza.',seq(['smooth','Uji permukaan licin','Blok bergerak lebih jauh.','🧊'],['rough','Uji permukaan kasar','Blok berhenti lebih awal.','🪨'],['compare','Banding jarak','Daya awal dikekalkan sama.','📏']),'🛷'),
  q('Banyak atau Sedikit Geseran?','force6','classify','Pilih keadaan yang memerlukan lebih atau kurang geseran.','Nilai kasut, brek dan bahagian mesin.','Geseran ditambah untuk cengkaman dan membrek, tetapi dikurangkan pada bahagian bergerak untuk memudahkan gerakan.',cls(['shoe','Tapak kasut bercorak','more','Corak meningkatkan cengkaman.','👟'],['brake','Brek basikal','more','Geseran membantu berhenti.','🚲'],['bearing','Pelincir pada gear','less','Mengurangkan geseran bahagian bergerak.','⚙️']),'⚙️'),
  q('Cabaran Daya','force6','design','Baiki troli supaya mudah bergerak dan berhenti selamat.','Pilih roda lancar, permukaan pemegang dan brek.','Reka bentuk menggunakan geseran mengikut fungsi: kurang pada gandar, lebih pada pemegang dan brek.',cls(['axle','Lincirkan gandar','yes','Mengurangkan geseran yang tidak diperlukan.','🛞'],['grip','Tambah pemegang bertekstur','yes','Meningkatkan cengkaman.','✋'],['brake','Pasang brek','yes','Geseran membantu troli berhenti.','🛑'],['oilbrake','Letak minyak pada brek','no','Mengurangkan geseran yang diperlukan.','⚠️']),'🛒')
 ]);
 u('speed','Kelajuan','🏎️','Ukur jarak dan masa untuk membandingkan kelajuan.',[
  q('Siapa Lebih Laju?','speed6','compare','Banding objek menggunakan jarak dan masa.','Perhatikan dua kereta bergerak jarak sama.','Bagi jarak yang sama, objek yang mengambil masa lebih singkat bergerak lebih laju.',seq(['a','Kereta A: 10 m dalam 5 s','Data A direkod.','🚗'],['b','Kereta B: 10 m dalam 2 s','Data B direkod.','🏎️'],['compare','Banding masa','Kereta B lebih laju.','⏱️']),'🏁'),
  q('Ukur Jarak','speed6','measure','Ukur jarak pada lintasan maya.','Tetapkan titik mula dan akhir lalu baca meter.','Jarak ialah panjang laluan antara titik mula dan akhir; unit mudah ialah meter (m).',seq(['start','Tanda titik mula 0 m','Ukuran bermula pada sifar.','0 m'],['end','Tanda titik akhir 12 m','Kedudukan akhir dicatat.','12 m'],['read','Rekod jarak 12 m','Perbezaan kedudukan dibaca.','📏']),'📏'),
  q('Ukur Masa','speed6','measure','Ukur masa perjalanan secara adil.','Mulakan dan hentikan jam pada peristiwa yang sama.','Masa perjalanan diukur dari objek mula bergerak hingga tiba di garisan akhir, dalam saat (s).',seq(['ready','Sediakan jam pada 0 s','Jam diset semula.','0 s'],['start','Mula bersama gerakan','Titik mula masa konsisten.','▶️'],['stop','Henti di garisan akhir','Masa 4 s direkod.','4 s']),'⏱️'),
  q('Kira Kelajuan','speed6','sequence','Gunakan jarak dan masa untuk menentukan kelajuan.','Masukkan 20 m dan 4 s pada model.','Kelajuan = jarak ÷ masa; 20 m ÷ 4 s = 5 m/s.',seq(['distance','Catat jarak 20 m','Jarak dalam meter.','20 m'],['time','Catat masa 4 s','Masa dalam saat.','4 s'],['divide','Bahagi 20 ÷ 4','Pengiraan menggunakan data.','÷'],['answer','Dapatkan 5 m/s','Unit menyatakan meter setiap saat.','5 m/s']),'🧮'),
  q('Perlumbaan Saintifik','speed6','sequence','Kumpul data dan tentukan objek terpantas.','Ukur tiga kereta pada lintasan maya sama.','Perbandingan kelajuan memerlukan jarak dan masa; nilai kelajuan terbesar ialah yang terpantas.',seq(['track','Tetapkan jarak 15 m','Semua kereta melalui jarak sama.','📏'],['a','Ukur A: 5 s','Kelajuan A ialah 3 m/s.','🚗'],['b','Ukur B: 3 s','Kelajuan B ialah 5 m/s.','🏎️'],['c','Ukur C: 6 s','Kelajuan C ialah 2.5 m/s.','🚙'],['result','Banding keputusan','B ialah yang terpantas.','🏆']),'🏁')
 ]);
 u('food-preservation','Pengawetan Makanan','🥫','Siasat kerosakan makanan dan kaedah pengawetan secara maya.',[
  q('Mengapa Makanan Rosak?','preservation6','sequence','Kenal pasti tanda kerosakan dan peranan mikroorganisma.','Perhatikan sampel fiksyen mengikut masa.','Mikroorganisma boleh menyebabkan makanan berubah bau, rupa atau tekstur; makanan diragui tidak boleh dirasa.',seq(['fresh','Periksa sampel awal','Tiada tanda kerosakan.','🍎'],['time','Majukan masa maya','Mikroorganisma mendapat masa untuk membiak.','⏩'],['signs','Perhatikan perubahan','Sampel maya menunjukkan tanda rosak.','⚠️']),'🧫'),
  q('Kenali Kaedah Pengawetan','preservation6','classify','Padankan kaedah dengan cara mengawal kerosakan.','Periksa pengeringan, penyejukan, pengasinan dan pembotolan.','Kaedah pengawetan menghalang atau memperlahankan pertumbuhan mikroorganisma melalui keadaan berbeza.',cls(['dry','Buah dikeringkan','drying','Air dikurangkan.','☀️'],['cold','Susu disejukkan','cold','Suhu rendah memperlahankan pertumbuhan.','❄️'],['salt','Ikan diasinkan','salt','Keadaan kurang sesuai untuk banyak mikroorganisma.','🧂'],['can','Makanan dalam tin tertutup','bottle','Pemprosesan dan bekas tertutup melindungi makanan.','🥫']),'📦'),
  q('Pilih Kaedah Sesuai','preservation6','classify','Padankan makanan dengan kaedah sesuai.','Gunakan ciri makanan dan tujuan penyimpanan.','Kaedah dipilih mengikut jenis makanan, tempoh simpanan dan keselamatan pemprosesan.',cls(['fish','Ikan untuk simpanan lama','cold','Pembekuan sesuai dalam model ini.','🐟'],['fruit','Hirisan buah','drying','Pengeringan mengurangkan air.','🍌'],['jam','Jem komersial','bottle','Pembotolan terkawal melindungi produk.','🫙']),'🍽️'),
  q('Hentikan Mikroorganisma','preservation6','compare','Banding faktor pertumbuhan dalam model makanan.','Ubah suhu atau kandungan air secara maya.','Pengawetan mengubah keadaan supaya pertumbuhan mikroorganisma diperlahankan atau dihentikan.',seq(['normal','Periksa suhu bilik','Pertumbuhan model lebih cepat.','🌡️'],['cold','Turunkan suhu','Pertumbuhan diperlahankan.','❄️'],['dry','Kurangkan air','Pertumbuhan turut diperlahankan.','☀️']),'🦠'),
  q('Makmal Pengawetan','preservation6','design','Bina pelan pengawetan maya yang selamat.','Pilih kaedah sesuai dan label penyimpanan.','Pengawetan selamat memerlukan kaedah sesuai, kebersihan, pembungkusan dan penyimpanan yang betul; simulasi ini bukan arahan pemprosesan di rumah.',cls(['method','Pilih kaedah mengikut makanan','yes','Kaedah sepadan dengan produk.','✅'],['label','Label tarikh dan cara simpan','yes','Maklumat membantu penggunaan selamat.','🏷️'],['taste','Rasa makanan yang diragui','no','Tidak selamat.','⛔']),'🧑‍🔬')
 ]);
 u('waste','Bahan Buangan','♻️','Kelaskan sisa dan urus bahan buangan secara bertanggungjawab.',[
  q('Kenali Bahan Buangan','waste6','classify','Kelaskan bahan buangan mengikut sumber.','Periksa sisa makanan, kertas dan bateri.','Bahan buangan datang daripada rumah, pertanian dan industri serta memerlukan pengurusan sesuai.',cls(['food','Sisa makanan rumah','biodegradable','Boleh diurai oleh organisma pengurai.','🍌'],['plastic','Botol plastik','nonbio','Terurai sangat perlahan.','🧴'],['battery','Bateri terpakai','nonbio','Perlu saluran kutipan khas.','🔋']),'🗑️'),
  q('Terbiodegradasi atau Tidak?','waste6','classify','Bezakan bahan yang boleh diurai secara biologi.','Periksa daun, kulit buah, kaca dan plastik.','Bahan terbiodegradasi boleh diuraikan oleh mikroorganisma; bahan lain kekal lebih lama dan perlu diurus betul.',cls(['leaf','Daun kering','biodegradable','Bahan organik boleh diurai.','🍂'],['peel','Kulit buah','biodegradable','Bahan organik boleh diurai.','🍌'],['glass','Botol kaca','nonbio','Tidak terbiodegradasi.','🍾'],['plastic','Beg plastik','nonbio','Tidak mudah diurai secara biologi.','🛍️']),'🌱'),
  q('Ke Mana Sampah Pergi?','waste6','sequence','Jejak bahan buangan selepas dikutip.','Pilih, asing dan hantar ke laluan sesuai.','Pengasingan di punca membolehkan kompos, guna semula, kitar semula atau pelupusan terkawal.',seq(['sort','Asingkan di punca','Jenis sisa dikenal pasti.','🗂️'],['recover','Pulihkan bahan berguna','Sisa makanan boleh dikompos dan bahan sesuai dikitar semula.','♻️'],['special','Asingkan sisa khas','Bateri dihantar ke pusat kutipan.','🔋'],['dispose','Lupus baki secara terkawal','Kesan kepada alam dikurangkan.','🚛']),'🏙️'),
  q('Kurangkan Bahan Buangan','waste6','classify','Utamakan tindakan mengurangkan sisa.','Nilai kurangkan, guna semula dan kitar semula.','Mengelakkan dan mengurangkan sisa biasanya lebih baik sebelum guna semula dan kitar semula.',cls(['bottle','Bawa botol boleh guna semula','reduce','Mengelakkan botol sekali guna.','🚰'],['box','Gunakan semula kotak','reuse','Memanjangkan hayat barang.','📦'],['paper','Kitar semula kertas bersih','recycle','Bahan diproses menjadi produk baharu.','📄']),'♻️'),
  q('Bandar Lestari','waste6','design','Urus masalah sisa komuniti maya.','Gabungkan pencegahan, pengasingan, kompos dan kutipan khas.','Bandar lestari mengurangkan sisa, menggunakan semula, mengasingkan bahan dan melupus baki dengan bertanggungjawab.',cls(['refill','Sediakan stesen isi semula','yes','Mengurangkan bekas sekali guna.','🚰'],['compost','Kompos sisa makanan','yes','Mengalihkan bahan organik daripada tapak pelupusan.','🌱'],['battery','Kutip bateri secara khas','yes','Mengelakkan pelupusan biasa.','🔋'],['burn','Bakar sampah terbuka','no','Mencemarkan udara dan berbahaya.','⛔']),'🏘️')
 ]);
 u('eclipses','Gerhana','🌘','Modelkan kedudukan Matahari, Bumi dan Bulan dengan selamat.',[
  q('Matahari, Bumi dan Bulan','eclipse6','model','Kenal pasti peranan cahaya dan bayang.','Susun sumber cahaya, Bumi dan Bulan pada model tidak berskala.','Gerhana melibatkan penjajaran Matahari, Bumi dan Bulan serta bayang; model ini tidak berskala.',seq(['sun','Letak Matahari','Matahari ialah sumber cahaya.','☀️'],['earth','Letak Bumi','Bumi menerima cahaya Matahari.','🌍'],['moon','Letak Bulan','Bulan bergerak mengelilingi Bumi.','🌕']),'🌌'),
  q('Gerhana Matahari','eclipse6','sequence','Modelkan gerhana Matahari dengan selamat.','Letakkan Bulan di antara Matahari dan Bumi.','Gerhana Matahari berlaku apabila Bulan berada di antara Matahari dan Bumi dan bayangnya jatuh pada sebahagian Bumi; jangan pandang Matahari secara langsung.',seq(['sun','Tetapkan Matahari','Sumber cahaya berada di satu sisi.','☀️'],['moon','Letak Bulan di tengah','Bulan menghalang sebahagian cahaya.','🌑'],['earth','Periksa bayang pada Bumi','Hanya kawasan tertentu mengalami gerhana.','🌍'],['safety','Baca nota keselamatan','Jangan melihat Matahari secara langsung.','🕶️']),'🌑'),
  q('Gerhana Bulan','eclipse6','sequence','Modelkan gerhana Bulan.','Letakkan Bumi di antara Matahari dan Bulan.','Gerhana Bulan berlaku apabila Bulan melalui bayang Bumi.',seq(['sun','Tetapkan Matahari','Cahaya bergerak ke arah Bumi.','☀️'],['earth','Letak Bumi di tengah','Bumi menghasilkan bayang.','🌍'],['moon','Gerakkan Bulan ke bayang','Bulan melalui bayang Bumi.','🌕']),'🌘'),
  q('Susun Kedudukan','eclipse6','classify','Bezakan dua jenis gerhana melalui kedudukan.','Periksa objek yang berada di tengah.','Bulan di tengah menghasilkan gerhana Matahari; Bumi di tengah menghasilkan gerhana Bulan.',cls(['sme','Matahari–Bulan–Bumi','solar','Bulan berada di tengah.','☀️🌑🌍'],['sem','Matahari–Bumi–Bulan','lunar','Bumi berada di tengah.','☀️🌍🌕']),'↔️'),
  q('Makmal Gerhana','eclipse6','simulate','Uji mengapa gerhana tidak berlaku setiap bulan.','Ubah kedudukan orbit Bulan pada model condong ringkas.','Gerhana memerlukan penjajaran tertentu; orbit Bulan condong, jadi penjajaran tepat tidak berlaku setiap bulan.',seq(['orbit','Periksa satah orbit Bulan','Orbit ditunjukkan condong dalam model.','⭕'],['month','Gerakkan Bulan satu pusingan','Kebanyakan kedudukan melepasi atas atau bawah bayang.','🌕'],['align','Cari penjajaran','Gerhana berlaku hanya dekat penjajaran yang sesuai.','🌘'],['scale','Semak label model','Jarak dan saiz tidak berskala.','📐']),'🔭')
 ]);
 u('constellations','Buruj','✨','Gunakan corak bintang sebagai panduan budaya dan bermusim.',[
  q('Corak Di Langit','constellation6','investigate','Kenal pasti corak daripada kedudukan bintang.','Sambungkan titik tanpa mengubah kedudukan bintang.','Buruj ialah corak yang manusia kenal pasti pada bintang yang kelihatan berdekatan dari Bumi.',seq(['dots','Periksa titik bintang','Kedudukan relatif diperhatikan.','✦'],['connect','Sambung corak','Garis ialah bantuan visual.','✨'],['compare','Banding tafsiran','Budaya boleh menamakan corak dengan cara berbeza.','🌌']),'✨'),
  q('Kenali Buruj','constellation6','classify','Padankan corak dengan nama pendidikan ringkas.','Periksa Biduk, Belantik dan Pari tanpa menganggap garis itu nyata.','Corak bintang membantu pengecaman langit; garis dan bentuk hanyalah panduan pendidikan.',cls(['dipper','Corak seperti senduk','north','Biduk membantu mencari arah utara di tempat dan masa sesuai.','🥄'],['orion','Corak tiga bintang sebaris','season','Belantik kelihatan pada musim tertentu.','⋆⋆⋆'],['crux','Corak seperti layang-layang','season','Pari dapat dilihat dari kawasan selatan pada keadaan sesuai.','◇']),'🔭'),
  q('Cari Arah','constellation6','sequence','Gunakan corak bintang sebagai panduan arah ringkas.','Ikut bintang penunjuk pada model Biduk.','Buruj boleh membantu anggaran arah apabila kelihatan, tetapi kedudukan, masa dan lokasi mesti dipertimbangkan.',seq(['find','Cari corak Biduk','Corak dikenal pasti.','🥄'],['pointer','Jejak bintang penunjuk','Arah pada model ditunjukkan.','↗️'],['north','Anggar arah utara','Anggaran disemak dengan kompas.','🧭']),'🧭'),
  q('Musim dan Buruj','constellation6','compare','Banding buruj yang kelihatan pada masa berbeza.','Ubah bulan dan masa pada simulator langit.','Buruj yang kelihatan berubah mengikut masa malam, musim, lokasi dan keadaan langit kerana Bumi bergerak.',seq(['month1','Periksa langit bulan pertama','Satu corak jelas kelihatan.','🌌'],['month2','Ubah beberapa bulan','Kedudukan dan corak kelihatan berubah.','🗓️'],['record','Rekod perbezaan','Pemerhatian bergantung pada masa dan lokasi.','📋']),'🌠'),
  q('Navigator Malam','constellation6','design','Gabungkan petunjuk langit dengan alat moden secara selamat.','Pilih corak, kompas dan semakan cuaca.','Buruj ialah salah satu petunjuk arah, tetapi navigasi selamat menggunakan beberapa sumber dan tidak bergantung pada corak yang terlindung awan.',cls(['pattern','Kenal pasti corak yang sah','yes','Corak sesuai dengan masa dan lokasi.','✨'],['compass','Semak dengan kompas','yes','Sumber kedua mengesahkan arah.','🧭'],['cloud','Andaikan buruj di sebalik awan','no','Tiada pemerhatian boleh dibuat.','☁️']),'🗺️')
 ]);
 u('machines','Mesin','⚙️','Nilai, baiki dan reka mesin majmuk untuk masalah harian.',[
  q('Mesin dan Kehidupan','machines6','evaluate','Nilai bagaimana mesin membantu kerja.','Banding masa, usaha dan keselamatan beberapa alat.','Mesin membantu melakukan kerja dengan lebih mudah, cepat atau selamat, tetapi perlu digunakan mengikut tujuan.',cls(['canopener','Pembuka tin','yes','Gabungan komponen membantu membuka penutup.','🥫'],['bicycle','Basikal','yes','Gear, roda dan gandar bekerjasama.','🚲'],['broken','Alat rosak digunakan juga','no','Tidak selamat dan tidak berfungsi baik.','⚠️']),'🧰'),
  q('Mesin Ringkas Bergabung','machines6','sequence','Jejak komponen dalam mesin majmuk.','Aktifkan roda, gear dan skru pada model.','Mesin majmuk menggabungkan dua atau lebih mesin ringkas atau mekanisme untuk menjalankan fungsi.',seq(['wheel','Putar roda dan gandar','Gerakan dimulakan.','🛞'],['gear','Pindahkan gerakan melalui gear','Arah atau kelajuan gerakan berubah.','⚙️'],['screw','Gerakkan skru','Putaran menghasilkan gerakan terkawal.','🔩']),'⚙️'),
  q('Kenal Pasti Komponen','machines6','classify','Kenal pasti fungsi komponen dalam reka bentuk.','Periksa roda, gear dan skru.','Setiap komponen menyumbang fungsi tertentu dalam sistem mesin.',cls(['wheel','Roda dan gandar','component','Membantu gerakan atau putaran.','🛞'],['gear','Gear','component','Memindahkan gerakan antara aci.','⚙️'],['screw','Skru','component','Mencantum atau menghasilkan gerakan terkawal.','🔩']),'🔍'),
  q('Baiki Reka Bentuk','machines6','diagnose','Diagnosis mesin maya yang tersekat.','Periksa gear tidak sejajar, gandar kasar dan penutup keselamatan.','Pembaikan reka bentuk menangani punca masalah sambil mengekalkan keselamatan.',cls(['align','Sejajarkan gear','improve','Gigi gear dapat bersentuhan betul.','⚙️'],['bearing','Kurangkan geseran gandar','improve','Putaran menjadi lebih lancar.','🛞'],['guard','Kekalkan penutup gear','improve','Bahagian bergerak terlindung.','🛡️']),'🧰'),
  q('Cipta Mesin Berguna','machines6','design','Reka mesin majmuk maya untuk mengangkat dan memindahkan kotak.','Pilih komponen, uji, nilai dan baiki.','Reka bentuk mesin yang baik menggabungkan komponen sesuai, diuji dengan bukti dan mempunyai ciri keselamatan.',cls(['wheels','Tambah roda dan gandar','yes','Kotak boleh dipindahkan dengan lebih mudah.','🛞'],['gear','Gunakan gear pada pemegang','yes','Gerakan boleh dipindahkan secara terkawal.','⚙️'],['guard','Tutup bahagian bergerak','yes','Pengguna dilindungi.','🛡️'],['sharp','Tambah bahagian tajam terbuka','no','Tidak selamat dan tidak membantu fungsi.','⛔']),'🏗️')
 ]);
})();
