'use strict';
window.MakmalYear3Domains.density={
 objects(d){return d.mode==='compare'?[['wood','Blok kayu','float'],['metal','Blok logam','sink']]:[['wood','Kayu','float'],['stone','Batu','sink'],['cork','Gabus','float']];},
 init(s){Object.assign(s,{selected:null,guess:null,results:{},sorted:{},salt:false,stirred:false,shape:'ball',cargo:0,ballTested:false,boatTested:false,result:null});},
 solved(s,d){if(d.mode==='salt')return !!s.results.fresh&&!!s.results.salt;if(d.mode==='boat')return s.ballTested&&s.boatTested&&s.shape==='boat'&&s.cargo===2&&s.result==='float';return d.mode==='sort'?Object.keys(s.sorted).length===this.objects(d).length:Object.keys(s.results).length===this.objects(d).length;},
 act(s,d,a,v){const ui=window.MakmalYear3UI;
  if(['test','compare','sort'].includes(d.mode)){
   if(a==='object'&&this.objects(d).some(x=>x[0]===v)){s.selected=v;s.guess=null;s.result=null;}
   if(a==='guess'&&s.selected&&['float','sink'].includes(v))s.guess=v;
   if(a==='test'&&s.selected&&s.guess){s.result=this.objects(d).find(x=>x[0]===s.selected)[2];s.results[s.selected]={guess:s.guess,result:s.result};ui.message(s,s.result==='float'?'Objek timbul di permukaan.':'Objek tenggelam ke dasar.');}
   if(a==='sort'&&s.selected&&s.results[s.selected]&&['float','sink'].includes(v)){if(s.results[s.selected].result===v){s.sorted[s.selected]=v;ui.message(s,'✓ Kumpulan sepadan dengan hasil ujian.');}else ui.message(s,'Gunakan hasil ujian, bukan ramalan awal.',false);}
  }
  if(d.mode==='salt'){
   if(a==='test'&&(!s.salt||s.stirred)){s.result=s.stirred?'float':'sink';s.results[s.stirred?'salt':'fresh']=s.result;ui.message(s,s.stirred?'Telur timbul dalam air garam model ini.':'Telur tenggelam dalam air biasa.');}
   if(a==='salt'&&s.results.fresh){s.salt=true;s.result=null;}
   if(a==='stir'&&s.salt)s.stirred=true;
  }
  if(d.mode==='boat'){
   if(a==='shape'&&s.ballTested&&['ball','boat'].includes(v)){s.shape=v;s.cargo=0;s.result=null;}
   if(a==='cargo'&&s.shape==='boat'&&s.cargo<4){s.cargo++;s.result=null;}
   if(a==='unload'&&s.cargo>0){s.cargo--;s.result=null;}
   if(a==='test'){s.result=s.shape==='boat'&&s.cargo<=2?'float':'sink';if(s.shape==='ball')s.ballTested=true;else s.boatTested=true;ui.message(s,s.result==='float'?'Kapal dan muatan timbul.':'Gumpalan atau muatan berlebihan tenggelam.');}
  }
 },
 hint(s,d){if(this.solved(s,d))return ['next',undefined,'Bandingkan keputusan ujian.'];if(d.mode==='salt')return !s.results.fresh?['test',undefined,'Uji telur dalam air biasa dahulu.']:!s.salt?['salt',undefined,'Tambah garam maya.']:!s.stirred?['stir',undefined,'Larutkan garam.']:['test',undefined,'Uji semula telur.'];if(d.mode==='boat')return !s.ballTested?['test',undefined,'Uji gumpalan kerajang dahulu.']:s.shape==='ball'?['shape','boat','Bentukkan kapal berongga.']:s.cargo<2?['cargo',undefined,'Tambah muatan kecil sehingga dua.']:s.cargo>2?['unload',undefined,'Kurangkan muatan sehingga dua.']:['test',undefined,'Uji kapal dengan dua muatan.'];const x=this.objects(d).find(x=>d.mode==='sort'?!s.sorted[x[0]]:!s.results[x[0]]);if(s.selected!==x[0])return ['object',x[0],'Pilih '+x[1]+'.'];if(!s.guess)return ['guess','float','Ramalkan dahulu tanpa takut salah.'];if(!s.results[x[0]])return ['test',undefined,'Lepaskan objek.'];return ['sort',x[2],'Kelaskan mengikut hasil yang diperhatikan.'];},
 render(s,d,active){const ui=window.MakmalYear3UI,b=ui.button;const label=d.mode==='salt'?'Telur':d.mode==='boat'?(s.shape==='ball'?'Kerajang bergumpal':'Kapal kerajang'):this.objects(d).find(x=>x[0]===s.selected)?.[1]||'Pilih objek';const y=s.result==='sink'?167:s.result==='float'?82:37;
 let scene=ui.svg(`<path d="M45 55V198H315V55" fill="#cbefff" stroke="#17659a" stroke-width="4"/><path d="M48 90Q95 82 135 90T220 90T311 90" fill="none" stroke="#147bac" stroke-width="3"/>${d.mode==='boat'&&s.shape==='boat'?`<path d="M135 ${y}h90l-18 25h-54z" fill="#afbdd2" stroke="#283e66"/><text x="180" y="${y-7}" text-anchor="middle">${s.cargo} muatan</text>`:`<ellipse cx="180" cy="${y}" rx="23" ry="18" fill="${s.selected==='wood'?'#b6804f':'#f4d277'}" stroke="#735532"/>`}<text x="180" y="217" text-anchor="middle">${s.result==='sink'?'↓ Tenggelam':s.result==='float'?'↑ Timbul':'Belum diuji'}</text>`,'Bekas air: '+label)+`<p><strong>${label}</strong> · ${d.mode==='salt'?(s.stirred?'Air garam':'Air biasa'):d.mode==='compare'?'Dua blok mempunyai isi padu sama.':'Model maya; bukan semua objek besar tenggelam.'}</p>`;
 if(active){if(d.mode==='salt')scene+=b('test',undefined,'Uji telur',s.salt&&!s.stirred)+b('salt',undefined,'Tambah garam',!s.results.fresh||s.salt)+b('stir',undefined,'Kacau hingga larut',!s.salt||s.stirred);else if(d.mode==='boat')scene+=b('test',undefined,'Uji dalam air')+b('shape','boat','Bentuk kapal berongga',!s.ballTested||s.shape==='boat')+b('cargo',undefined,'Tambah muatan',s.shape!=='boat'||s.cargo>=4)+b('unload',undefined,'Kurangkan muatan',!s.cargo);else scene+=`<div class="y3-choices">${this.objects(d).map(x=>b('object',x[0],x[1],false,s.selected===x[0])).join('')}</div>`+b('guess','float','Ramalan: timbul',!s.selected,s.guess==='float')+b('guess','sink','Ramalan: tenggelam',!s.selected,s.guess==='sink')+b('test',undefined,'Lepaskan dan uji',!s.guess)+(d.mode==='sort'?b('sort','float','Kumpulan timbul',!s.results[s.selected])+b('sort','sink','Kumpulan tenggelam',!s.results[s.selected]):'');}
 return scene+`<div class="y3-records">${Object.entries(s.results).map(([id,r])=>`<p>✓ ${id==='fresh'?'Air biasa':id==='salt'?'Air garam':this.objects(d).find(x=>x[0]===id)?.[1]}: ${(r.result||r)==='float'?'Timbul':'Tenggelam'}${r.guess?' · ramalan '+(r.guess==='float'?'timbul':'tenggelam'):''}${s.sorted[id]?' · Dikelaskan ✓':''}</p>`).join('')}</div>`;
 }
};
window.MakmalYear3Domains.propagation={
 init(s){Object.assign(s,{method:null,water:false,light:false,days:0,grown:{}});},
 solved(s){return !!s.grown.seed&&!!s.grown.stem;},
 act(s,d,a,v){if(a==='method'&&['seed','stem'].includes(v)){s.method=v;s.water=false;s.light=false;s.days=0;}if(a==='water'&&s.method)s.water=true;if(a==='light'&&s.method)s.light=true;if(a==='day'&&s.method&&s.water&&s.light&&s.days<3){s.days++;if(s.days===3)s.grown[s.method]=true;window.MakmalYear3UI.message(s,s.days===3?'Akar dan pucuk baharu terbentuk dalam model.':'Masa maya berlalu. Perhatikan pertumbuhan.');}},
 hint(s){if(this.solved(s))return ['next',undefined,'Bandingkan dua cara pembiakan.'];if(!s.method||s.grown[s.method])return ['method',s.grown.seed?'stem':'seed','Pilih satu bahan pembiakan.'];return !s.water?['water',undefined,'Sediakan air secukupnya.']:!s.light?['light',undefined,'Letakkan di tempat bercahaya sesuai.']:['day',undefined,'Majukan masa maya.'];},
 render(s,d,active){const ui=window.MakmalYear3UI,b=ui.button;return ui.svg(`<path d="M110 160h140l-20 50h-100z" fill="#c9895a"/><path d="M180 160v-${20+s.days*25}" stroke="#238344" stroke-width="9"/>${s.days>0?`<path d="M180 ${150-s.days*20}q-70-40-40-50q40-3 40 50q60-55 65-25q-3 28-65 25" fill="#61b844"/>`:''}<text x="30" y="30">${s.light?'☀ Cahaya':'Cahaya belum disediakan'}</text><text x="30" y="55">${s.water?'Air cukup':'Air belum disediakan'}</text>`,'Model pertumbuhan daripada '+(s.method==='stem'?'keratan batang':'biji benih'))+`<p>${s.method==='stem'?'Keratan batang bunga raya':s.method==='seed'?'Biji kacang hijau':'Pilih bahan'} · Peringkat ${s.days} / 3. Masa dipercepat, bukan tempoh sebenar.</p>${active?b('method','seed','Tanam biji benih')+b('method','stem','Tanam keratan batang')+b('water',undefined,'Sediakan air',!s.method||s.water)+b('light',undefined,'Sediakan cahaya',!s.method||s.light)+b('day',undefined,'Majukan masa maya',!s.water||!s.light||s.days===3):''}<p>${s.grown.seed?'✓ Biji menjadi anak pokok.':''} ${s.grown.stem?'✓ Keratan berakar dan bertunas.':''}</p>`;}
};
