'use strict';
window.MakmalYear3Screens=(()=>{
 const p=()=>window.MakmalProgress.forYear(3),units=()=>window.MakmalYear3.units;
 const art=u=>`<img class="unit-art" src="${u.icon||'assets/experiments/year3/icon-'+u.id+'.svg'}" alt="" width="88" height="88">`;
 const heading=(title,sub)=>`<div class="screen-heading"><p class="section-kicker">SAINS TAHUN 3</p><h1>${title}</h1><p>${sub}</p></div>`;
 function render(name,context){const progress=p();
  if(name==='year3')return heading('Sains Tahun 3','Sepuluh unit untuk membanding, mengukur dan mengelas.')+`<div class="year-progress"><span>${progress.completedTotal()} / 50 eksperimen selesai · ${progress.completedUnits()} / 10 unit selesai</span>${progress.isYearComplete()?'<button class="primary" data-route="year3Complete">Lihat Sambutan Tahun 3</button>':''}</div><div class="units-grid hub-grid">${units().map((u,i)=>`<button class="unit-card hub-card" data-y3unit="${u.id}">${art(u)}<span class="unit-copy"><small>UNIT ${String(i+1).padStart(2,'0')}</small><strong>${u.title}</strong><span class="unit-description">${u.description}</span></span><span class="unit-summary"><span>${progress.completedCount(u.id)} / 5 eksperimen</span><span class="badge">${progress.isUnitComplete(u.id)?'Selesai':progress.completedCount(u.id)?'Sedang Diterokai':'Belum Dimainkan'}</span></span></button>`).join('')}</div>`;
  if(name==='year3Complete')return `<section class="year-finale unit-celebration"><h1>SAINS TAHUN 3 SELESAI!</h1>${window.MakmalPico.dialogue('Hebat! Lima puluh penyiasatan sudah selesai. Teruskan memerhati dan bertanya!','success')}<p class="unit-count">${progress.completedUnits()} / 10 unit selesai</p><p class="unit-count">${progress.completedTotal()} / 50 eksperimen</p><ul class="year-unit-list">${units().map(u=>`<li>✓ ${u.title}</li>`).join('')}</ul>${window.MakmalMaster?.completionButton?.()||''}<div class="completion-actions"><button class="primary" data-route="year3">Kembali ke Tahun 3</button><button class="nav-button" data-route="year3">Main Semula Unit</button><button class="nav-button" data-action="home">Menu Utama</button></div></section>`;
  const u=units().find(u=>u.id===context.unitId);return heading(u.title,'5 eksperimen untuk diterokai')+`<div class="unit-intro">${art(u)}<p>${u.description}<br>${progress.completedCount(u.id)} / 5 eksperimen</p></div><div class="mission-list">${u.missions.map(m=>{const done=progress.isMissionComplete('mission'+m.number,u.id),available=progress.isAvailable(m.number,u.id);return `<button class="mission-card ${available?'mission-next':''}" data-y3mission="${m.id}" data-y3id="${u.id}" aria-disabled="${!available}"><span class="mission-number">${m.number}</span><span class="mission-copy"><small>MISI ${m.number}</small><strong>${m.title}</strong><span>${m.description}</span></span><span class="badge">${done?'Selesai':available?'Seterusnya':'Akan Datang'}</span></button>`;}).join('')}</div>`;
 }
 function completion(d,celebrate){const progress=p(),u=units().find(u=>u.id===d.unitId),finale=d.number===5||celebrate;
  return `<div class="completion mission-celebration"><span class="completion-check">✓</span><h2 id="activity-heading" tabindex="-1">Misi Selesai</h2><p class="discovery-copy">${d.discovery}</p>${finale?`<section class="unit-finale"><h3>${progress.isUnitComplete(u.id)?'UNIT '+u.title.toUpperCase()+' SELESAI!':'Kemajuan '+u.title}</h3><p class="unit-count">${progress.completedCount(u.id)} / 5 misi selesai</p><ul>${u.missions.map(m=>`<li>${progress.isMissionComplete('mission'+m.number,u.id)?'✓ Selesai':'○ Belum selesai'} · ${m.title}</li>`).join('')}</ul></section>`:''}${progress.isYearComplete()?'<section class="year-progress"><strong>SAINS TAHUN 3 SELESAI!</strong><p>10 / 10 unit selesai · 50 / 50 eksperimen</p><button class="primary" data-exp="yearComplete">Raikan Penemuan Tahun 3</button></section>':''}${window.MakmalMaster?.completionButton?.()||''}<div class="completion-actions"><button class="primary" data-exp="restart">Main Semula ↻</button><button class="nav-button" data-exp="exit">Kembali ke Senarai Misi</button><button class="nav-button" data-exp="year2">Kembali ke Tahun 3</button></div></div>`;
 }
 return {render,completion};
})();
