'use strict';
window.MakmalYear3Domains.solar={
 init(s){Object.assign(s,{seen:[],selected:null,hottest:false,ticks:0,inner:null,outer:null});},
 solved(s,d){return d.mode==='temperature'?s.seen.length===4&&s.hottest:s.ticks>=8&&(d.mode!=='finale'||s.inner==='earth'&&s.outer==='neptune');},
 act(s,d,a,v){if(a==='planet'&&['mercury','venus','earth','neptune'].includes(v)){s.selected=v;if(!s.seen.includes(v))s.seen.push(v);}if(a==='hottest'&&s.seen.length===4){s.hottest=v==='venus';window.MakmalYear3UI.message(s,s.hottest?'Zuhrah paling panas walaupun bukan paling dekat.':'Bandingkan suhu Zuhrah dengan yang lain.',s.hottest);}if(a==='inner'&&['earth','neptune'].includes(v))s.inner=v;if(a==='outer'&&['earth','neptune'].includes(v))s.outer=v;if(a==='tick'&&(d.mode==='orbit'||d.mode==='finale'&&s.inner==='earth'&&s.outer==='neptune')&&s.ticks<16){s.ticks++;s.effect='observation';}},
 hint(s,d){if(this.solved(s,d))return ['next',undefined,'Bandingkan pemerhatian.'];if(d.mode==='temperature'){const id=['mercury','venus','earth','neptune'].find(id=>!s.seen.includes(id));return id?['planet',id,'Periksa setiap planet.']:['hottest','venus','Zuhrah memerangkap haba dengan atmosferanya.'];}if(d.mode==='finale'){if(s.inner!=='earth')return ['inner','earth','Bumi lebih dekat kepada Matahari daripada Neptun.'];if(s.outer!=='neptune')return ['outer','neptune','Letakkan Neptun pada orbit lebih jauh.'];}return ['tick',undefined,'Majukan masa untuk melihat peredaran.'];},
 render(s,d,active){const ui=window.MakmalYear3UI,b=ui.button;
  if(d.mode==='temperature'){const rows=[['mercury','Utarid',3,'Dekat Matahari; suhu siang sangat panas dan malam sangat sejuk.'],['venus','Zuhrah',4,'Paling panas: atmosfera tebal memerangkap haba.'],['earth','Bumi',2,'Lebih sederhana berbanding Zuhrah.'],['neptune','Neptun',1,'Jauh daripada Matahari dan sangat sejuk.']];return `<div class="y3-cards">${rows.map(([id,name,n,text])=>`<button class="y3-card" data-exp="planet" data-value="${id}" ${!active?'disabled':''} aria-pressed="${s.selected===id}"><span class="planet-dot planet-${id}" aria-hidden="true"></span><strong>${name}</strong>${s.seen.includes(id)?`<span>${text}</span><span class="heat-meter" style="--heat:${n}">Tahap model: ${n}</span>`:'Periksa suhu'}</button>`).join('')}</div><p>Perbandingan ringkas, bukan suhu atau saiz mengikut skala.</p>${active?rows.map(([id,name])=>b('hottest',id,'Paling panas: '+name,s.seen.length<4)).join(''):''}`;}
  const years=s.ticks/4,period=d.mode==='finale'?165:1.88,angle1=years*Math.PI*2,angle2=years/period*Math.PI*2;
  const x1=180+54*Math.cos(angle1),y1=105+40*Math.sin(angle1),x2=180+145*Math.cos(angle2),y2=105+87*Math.sin(angle2);
  return ui.svg(`<ellipse cx="180" cy="105" rx="54" ry="40" fill="none" stroke="#78a5d3"/><ellipse cx="180" cy="105" rx="145" ry="87" fill="none" stroke="#78a5d3"/><circle cx="180" cy="105" r="22" fill="#ffd539"/><circle cx="${x1}" cy="${y1}" r="9" fill="#118acd"/><circle cx="${x2}" cy="${y2}" r="10" fill="#b57655"/><text x="180" y="215" text-anchor="middle">Matahari di pusat orbit</text>`,'Dua orbit, model tidak mengikut skala')+`<p><strong>Rajah tidak mengikut skala saiz atau jarak.</strong> Setiap langkah masa: ¼ tahun Bumi.</p><div class="y3-records"><p>Bumi: ${years.toFixed(2)} pusingan</p><p>${d.mode==='finale'?'Neptun':'Marikh'}: ${(years/period).toFixed(3)} pusingan</p></div><p>${d.mode==='finale'?'Neptun mengambil kira-kira 165 tahun Bumi bagi satu peredaran.':'Marikh mengambil hampir dua tahun Bumi bagi satu peredaran.'}</p>${active?(d.mode==='finale'?b('inner','earth','Orbit dekat: Bumi',false,s.inner==='earth')+b('inner','neptune','Orbit dekat: Neptun',false,s.inner==='neptune')+b('outer','earth','Orbit jauh: Bumi',false,s.outer==='earth')+b('outer','neptune','Orbit jauh: Neptun',false,s.outer==='neptune'):'')+b('tick',undefined,'Majukan masa ¼ tahun',s.ticks>=16||d.mode==='finale'&&(s.inner!=='earth'||s.outer!=='neptune')):''}<p>${Math.min(s.ticks,8)} / 8 langkah pemerhatian</p>`;
 }
};
window.MakmalYear3Domains.pulley={
 init(s,d){Object.assign(s,{parts:d.mode==='build'?[]:['wheel','rope','load'],position:0,up:false,down:false});},
 solved(s,d){return s.parts.length===3&&(d.mode==='direction'?s.up&&s.down:s.position===3);},
 act(s,d,a,v){if(a==='attach'&&['wheel','rope','load'][s.parts.length]===v)s.parts.push(v);if(s.parts.length===3){if(a==='pull'&&s.position<3){s.position++;s.up=true;window.MakmalYear3UI.message(s,'Tali ditarik ke bawah; beban naik.');}if(a==='lower'&&s.position>0){s.position--;s.down=true;window.MakmalYear3UI.message(s,'Tali dikendurkan secara terkawal; beban turun.');}}},
 hint(s,d){if(this.solved(s,d))return ['next',undefined,'Perhatikan arah tali dan beban.'];if(s.parts.length<3)return ['attach',['wheel','rope','load'][s.parts.length],'Pasang roda, tali dan beban mengikut urutan.'];if(d.mode==='direction'&&s.up&&!s.down)return ['lower',undefined,'Kendurkan tali secara terkawal.'];return ['pull',undefined,'Tarik hujung tali ke bawah.'];},
 render(s,d,active){const ui=window.MakmalYear3UI,b=ui.button,y=164-s.position*25,end=85+s.position*25;
  return ui.svg(`<path d="M95 15H260M180 15V45" stroke="#355276" stroke-width="8"/>${s.parts.includes('wheel')?`<circle cx="180" cy="62" r="25" fill="#ffd539" stroke="#176b9e" stroke-width="5"/><circle cx="180" cy="62" r="6" fill="#176b9e"/>`:''}${s.parts.includes('rope')?`<path d="M155 ${y}V62a25 25 0 0 1 50 0V${end}" stroke="#b47b3c" stroke-width="5" fill="none"/><path d="M228 ${end-15}v25m-7-8 7 8 7-8" fill="none" stroke="#d63d2f" stroke-width="3"/>`:''}${s.parts.includes('load')?`<rect x="125" y="${y}" width="60" height="36" rx="5" fill="#b4e2ff"/><text x="155" y="${y+24}" text-anchor="middle">Beban</text>`:''}<text x="245" y="130">Tali ↓</text><text x="28" y="130">Beban ↑</text>`,'Model takal tetap: roda kekal di atas, tali dan beban bergerak bertentangan')+`<p>Roda tetap pada sokongan. Kedudukan beban: ${s.position} / 3. ${s.up?'✓ Pernah naik.':''} ${s.down?'✓ Pernah turun.':''}</p>${active?(d.mode==='build'?['wheel','rope','load'].map((id,i)=>b('attach',id,['Pasang roda','Lalukan tali','Pasang beban'][i],s.parts.includes(id))).join(''):'')+b('pull',undefined,'Tarik tali ke bawah',s.parts.length!==3||s.position===3)+b('lower',undefined,'Kendurkan secara terkawal',s.parts.length!==3||s.position===0):''}<p class="y3-evidence">Takal tetap menukar arah tarikan, bukan mengurangkan berat beban.</p>`;
 }
};
